package com.runeshift.nuzbridge

import org.json.JSONArray
import org.json.JSONObject
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress
import java.net.SocketTimeoutException

/**
 * RetroArch RAM producer — the high-fidelity path. Polls RetroArch's UDP
 * network-command interface (READ_CORE_MEMORY, port 55355; the user enables
 * Settings ▸ Network ▸ Network Commands in RetroArch) and emits exact game
 * state: species, levels, HP, route, and battle on/off.
 *
 * Direct port of the validated desktop reference (_tools/memory-bridge.mjs).
 * All addresses/tables come from the game's memory profile JSON
 * (assets/memory/<game>.json, generated by _tools/dump-memory-profile.mjs and
 * verified live against RetroArch+mGBA on 2026-08-17: party @0x02024284 with
 * UNENCRYPTED species u16 @+32 (CFRU), enemy @0x0202402C (+100 = doubles
 * partner), gMapHeader section @0x02036DFC+0x14, gMain.inBattle @0x03003529).
 */
class MemoryProducer(private val profile: MemoryProfile) {

    @Volatile var running = false
        private set
    @Volatile var lastError: String = "—"
    @Volatile var lastStateSummary: String = "—"
    @Volatile var readsOk = 0L
    @Volatile var readsFailed = 0L

    private var thread: Thread? = null
    private var lastJson: String? = null
    private var lastBroadcastAt = 0L
    /** Drives the poll interval — see loop(). */
    @Volatile private var inBattleNow = false
    /** Consecutive polls that read "not in battle"; see the hysteresis below. */
    private var battleFalseStreak = 0
    // PC boxes, swept ONE box per poll rather than all at once: the full
    // storage is 14x30x80 = 33.6 KB, which as a single burst would stall the
    // loop, but a box at a time is ~3 extra reads and covers everything every
    // ~14 s. Cached per box so the emitted list stays complete between sweeps.
    private val boxContents = Array(14) { mutableListOf<JSONObject>() }
    private val boxSweptAt = LongArray(14)
    private var boxCursor = 0

    fun start() {
        if (running) return
        running = true
        thread = Thread({ loop() }, "nuz-memory-producer").apply { isDaemon = true; start() }
    }

    fun stop() {
        running = false
        thread = null
    }

    /** True only when detection is CONFIDENT and disagrees with this profile. */
    private fun mismatched(): Boolean {
        val d = GameDetect.lastGame ?: return false   // unrecognised → trust the user
        return d != profile.game
    }

    private fun loop() {
        var sock = DatagramSocket().apply { soTimeout = 800 }
        val addr = InetAddress.getByName("127.0.0.1")
        var deadPolls = 0
        var ticks = 0L
        try {
            while (running) {
                val okBefore = readsOk
                // Check the cartridge before the first poll, then every ~10 s.
                // Doing it first matters: otherwise the opening poll of a
                // freshly-switched game emits a full wrong-profile roster
                // before detection ever runs.
                if (ticks == 0L || ticks % 10L == 0L) {
                    try { detectGame(sock, addr) } catch (e: Throwable) { /* best-effort */ }
                }
                ticks++
                if (mismatched()) {
                    // Wrong profile for the running game: emit NOTHING. A wrong
                    // roster is worse than no roster — it writes other games'
                    // Pokemon into the run and there is no undo for that.
                    lastError = "Wrong profile — RetroArch is running " +
                        "${GameDetect.lastGame} but this is ${profile.game}. Switching…"
                    lastStateSummary = "[${profile.game}] paused — wrong game loaded"
                    Thread.sleep(1000L)
                    continue
                }
                try { pollOnce(sock, addr) } catch (e: Throwable) {
                    readsFailed++
                    lastError = "poll: ${e.message ?: e.javaClass.simpleName}"
                }
                if (readsOk > okBefore) {
                    deadPolls = 0
                    // Clear a stale failure message once reads are landing again.
                    // lastError was previously write-only, so a single transient
                    // timeout left "RetroArch not responding" on screen forever
                    // while data was visibly flowing — reported as "says live and
                    // I can see memory data, but also shows the not-connected
                    // error". Only clear messages WE own; a profile-mismatch
                    // warning is still true regardless of read health.
                    if (lastError.startsWith("RetroArch not responding") ||
                        lastError.startsWith("read: ") || lastError.startsWith("poll: ")) {
                        lastError = "—"
                    }
                } else {
                    deadPolls++
                }
                // Nothing at all got through for several polls: assume the socket
                // itself is poisoned and replace it. This is precisely what
                // toggling the memory switch by hand was doing.
                if (deadPolls >= 3) {
                    runCatching { sock.close() }
                    sock = try { DatagramSocket().apply { soTimeout = 800 } } catch (e: Exception) { sock }
                    deadPolls = 0
                    lastError = "socket reset — reconnecting to RetroArch"
                }
                // In battle the interesting state is TRANSIENT: the target-select
                // screen is frequently open for well under a second, so a 1 Hz
                // poll walks straight past it and the panel never sees the cursor
                // move (field report: turn focus followed, target focus didn't).
                // Overworld state changes at walking pace, so keep 1 Hz there.
                Thread.sleep(if (inBattleNow) 400L else 1000L)
            }
        } finally {
            runCatching { sock.close() }
        }
    }

    /**
     * Ask RetroArch what it is running. One packet, every few seconds — cheap
     * next to the ~11 reads a poll already costs, and it is the only thing in
     * the loop that can catch "the profile is decoding the wrong cartridge".
     */
    private fun detectGame(sock: DatagramSocket, addr: InetAddress) {
        val ctx = BridgeCore.appContext ?: return
        val out = "GET_STATUS".toByteArray()
        val buf = ByteArray(512)
        val pkt = DatagramPacket(buf, buf.size)
        val reply = try {
            sock.send(DatagramPacket(out, out.size, addr, 55355))
            sock.receive(pkt)
            String(pkt.data, 0, pkt.length)
        } catch (e: Exception) { return }   // detection is best-effort, never fatal
        if (!reply.startsWith("GET_STATUS")) return
        val r = GameDetect.parse(ctx, reply)
        GameDetect.record(r)
        // A recognised game that is not the one we are decoding means every
        // number this producer is about to emit is wrong. Hand it to BridgeCore,
        // which owns profile loading and the tracker socket.
        if (r.game != null && r.game != profile.game) BridgeCore.onGameDetected(r.game)
    }

    private fun read(sock: DatagramSocket, addr: InetAddress, at: Long, len: Int): ByteArray? {
        val cmd = "READ_CORE_MEMORY ${at.toString(16)} $len"
        val out = cmd.toByteArray()
        val buf = ByteArray(16 + len * 3 + 32)
        val pkt = DatagramPacket(buf, buf.size)
        // The SEND has to be inside the try as well. If RetroArch is momentarily
        // gone — which is exactly what a savestate load looks like — the socket
        // takes an ICMP port-unreachable and Java then throws
        // PortUnreachableException, NOT a timeout. That escaped this function,
        // aborted the whole poll before anything could be broadcast, and kept
        // throwing on the same socket forever: the feed went silent permanently
        // and only creating a new socket (toggling the memory switch) revived it.
        return try {
            sock.send(DatagramPacket(out, out.size, addr, 55355))
            sock.receive(pkt)
            val parts = String(pkt.data, 0, pkt.length).trim().split(" ")
            if (parts.size < 3 || parts[0] != "READ_CORE_MEMORY" || parts[2] == "-1") { readsFailed++; null }
            else {
                readsOk++
                ByteArray(parts.size - 2) { i -> parts[i + 2].toInt(16).toByte() }
            }
        } catch (e: SocketTimeoutException) {
            readsFailed++
            lastError = "RetroArch not responding on :55355 — enable Network Commands"
            null
        } catch (e: Exception) {
            // Any other socket fault: report it and let the loop decide whether
            // the socket needs replacing. Never let it escape the poll.
            readsFailed++
            lastError = "read: ${e.javaClass.simpleName}"
            null
        }
    }

    /**
     * Read a whole party (count x 100 bytes) in ONE request instead of one per
     * slot. Poll cost had crept to ~22 UDP round trips per tick, and at the
     * faster in-battle cadence that saturated the link — every read carries an
     * 800 ms timeout, so a few slow ones stall the entire poll and the battle
     * never appears. Batching takes a double battle from ~22 reads to ~11,
     * fewer than before the cursor work was added.
     *
     * Falls back to per-slot reads if the bulk response comes back short, so a
     * stricter RetroArch build degrades in speed rather than breaking.
     */
    private fun readParty(sock: DatagramSocket, addr: InetAddress, base: Long, count: Int): List<ByteArray?> {
        if (count <= 0) return emptyList()
        val want = count * 100
        val blk = read(sock, addr, base, want)
        if (blk != null && blk.size >= want) {
            return (0 until count).map { blk.copyOfRange(it * 100, it * 100 + 100) }
        }
        return (0 until count).map { read(sock, addr, base + it * 100L, 100) }
    }

    private fun u16(b: ByteArray, o: Int) = ((b[o].toInt() and 0xFF)) or ((b[o + 1].toInt() and 0xFF) shl 8)
    private fun u32(b: ByteArray, o: Int) =
        ((b[o].toInt() and 0xFF).toLong()) or ((b[o + 1].toInt() and 0xFF).toLong() shl 8) or
        ((b[o + 2].toInt() and 0xFF).toLong() shl 16) or ((b[o + 3].toInt() and 0xFF).toLong() shl 24)

    /** Gen-3 party mon → (speciesName, level, hp, maxHp, status) or null. */
    fun decodeMon(b: ByteArray?): JSONObject? {
        if (b == null || b.size < 100) return null
        val personality = u32(b, 0)
        val otId = u32(b, 4)
        if (personality == 0L && otId == 0L) return null
        // CFRU: unencrypted, fixed order — species u16 @+32. Vanilla fallback:
        // classic substructure decrypt.
        var species = u16(b, 32)
        if (species !in 1..2999) {
            val key = personality xor otId
            val order = ORDERS[(personality % 24).toInt()]
            val gOff = 32 + order.indexOf('G') * 12
            species = ((u32(b, gOff) xor key) and 0xFFFF).toInt()
        }
        if (species !in 1..2999) return null
        // exp lives in the Growth block: CFRU plain u32 @+36 (verified: the
        // captured Lv10 Gible reads 560 = the exact Medium-Slow threshold);
        // encrypted vanilla: Growth word 1 (offset gOff+4, XOR key).
        var exp = u32(b, 36).toInt()
        if (u16(b, 32) != species) {
            val key = personality xor otId
            val gOff = 32 + ORDERS[(personality % 24).toInt()].indexOf('G') * 12
            exp = (u32(b, gOff + 4) xor key).toInt()
        }
        val o = JSONObject()
        o.put("species", profile.speciesById[species] ?: "#$species")
        // Nickname: 10 bytes at +8, in the Gen-3 character encoding. Worth
        // having for its own sake, but it also makes roster matching far more
        // reliable than species alone — species collides across duplicates and
        // breaks on regional-form spelling, whereas the nickname is what the
        // player actually recognises the mon by.
        decodeG3(b, 8, 10)?.let { if (it.isNotEmpty()) o.put("nickname", it) }
        // Held item: Growth block u16 @+34 (plain) / word0 high half (encrypted).
        if (profile.itemsById.isNotEmpty()) {
            var itemId = u16(b, 34)
            if (u16(b, 32) != species) {
                val key = personality xor otId
                val gOff = 32 + ORDERS[(personality % 24).toInt()].indexOf('G') * 12
                itemId = (((u32(b, gOff) xor key) shr 16) and 0xFFFFL).toInt()
            }
            // Always present when the producer supports items: "" = holding
            // nothing (lets the tracker mirror consumption without ambiguity
            // against older producers that never send the field).
            o.put("item", if (itemId in 1..1299) profile.itemsById[itemId] ?: "" else "")
        }
        val lv = b[84].toInt() and 0xFF
        o.put("level", lv)
        o.put("nature", NATURES[(personality % 25).toInt()])
        profile.growthById[species]?.let { g ->
            if (lv in 1..99) {
                val cur = expAt(g, lv); val next = expAt(g, lv + 1)
                if (next > cur) o.put("expPct", ((exp - cur).coerceIn(0, next - cur)) * 100 / (next - cur))
            } else if (lv == 100) o.put("expPct", 100)
        }
        // Actual moveset: Attacks block (CFRU plain @+44: 4×u16 move ids —
        // verified live: Gible read Tackle/Sand Attack/Metal Claw; encrypted
        // vanilla: A-substructure words). Lets the tracker keep rosters'
        // movesets game-true instead of prompting off learnsets.
        if (profile.movesById.isNotEmpty()) {
            var aOff = 44
            var akey = 0L
            if (u16(b, 32) != species) {
                akey = personality xor otId
                aOff = 32 + ORDERS[(personality % 24).toInt()].indexOf('A') * 12
            }
            val moves = JSONArray()
            for (i in 0 until 4) {
                val raw = if (akey == 0L) u16(b, aOff + i * 2).toLong()
                          else ((u32(b, aOff + (i / 2) * 4) xor akey) shr ((i % 2) * 16)) and 0xFFFFL
                val id = raw.toInt()
                if (id in 1..1399) profile.movesById[id]?.let { moves.put(it) }
            }
            if (moves.length() > 0) o.put("moves", moves)
        }
        // EVs (E-substruct: 6 bytes) and IVs (M-substruct word, 5 bits each).
        // CFRU plain: E @+56, M @+68 (IV word @+72). Game stat order is
        // HP,Atk,Def,SPEED,SpA,SpD — the tracker wants HP,Atk,Def,SpA,SpD,Spe,
        // so slots 3..5 are reordered on the way out.
        run {
            var eOff = 56; var mOff = 68; var xkey = 0L
            if (u16(b, 32) != species) {
                xkey = personality xor otId
                val order = ORDERS[(personality % 24).toInt()]
                eOff = 32 + order.indexOf('E') * 12
                mOff = 32 + order.indexOf('M') * 12
            }
            val ge = IntArray(6)
            for (i in 0 until 6) {
                val w = u32(b, eOff + (i / 4) * 4) xor xkey
                ge[i] = ((w shr ((i % 4) * 8)) and 0xFF).toInt()
            }
            val ivWord = u32(b, mOff + 4) xor xkey
            // Gen-3 packs the ability SLOT into bit 31 of the same word as the
            // IVs (30 bits of IVs + isEgg + abilityNum). We send the slot rather
            // than a name: the tracker already knows each species' ability list,
            // so an index is all it needs and we avoid dragging an ability-name
            // table out of the ROM. NOTE this only distinguishes slots 0 and 1 —
            // a hidden ability needs more than this bit and is not resolved here.
            val abilitySlot = ((ivWord shr 31) and 1L).toInt()
            o.put("abilitySlot", abilitySlot)
            // Resolve to a NAME when the profile carries the ROM's ability table.
            // The tracker's own lists are empty for hack-specific species, so
            // sending the name is what makes this work for every mon rather than
            // only the mainline ones.
            profile.abilityBySpecies[species]?.let { list ->
                val pick = list.getOrNull(abilitySlot) ?: list.getOrNull(0)
                if (pick != null) o.put("ability", pick)
            }
            profile.typeBySpecies[species]?.let { types ->
                if (types.isNotEmpty()) o.put("types", JSONArray(types))
            }
            val gi = IntArray(6) { ((ivWord shr (it * 5)) and 0x1F).toInt() }
            val toTracker = { g: IntArray -> intArrayOf(g[0], g[1], g[2], g[4], g[5], g[3]) }
            val evs = toTracker(ge); val ivs = toTracker(gi)
            if (evs.all { it in 0..255 }) o.put("evs", JSONArray(evs.toList()))
            o.put("ivs", JSONArray(ivs.toList()))
        }
        o.put("hp", u16(b, 86))
        o.put("maxHp", u16(b, 88))
        // The cartridge's OWN computed stats live right here in the party
        // struct (+88..98, game order hp,atk,def,SPEED,spAtk,spDef). Sending
        // them lets the tracker DISPLAY what the summary screen shows instead
        // of recomputing it — recomputation drifts by a point whenever an IV
        // is stale or a hack rebalanced a base stat, which is exactly the
        // off-by-one the user reported. Emitted in the tracker's stat order
        // (hp,atk,def,spa,spd,spe).
        run {
            val st = JSONArray()
            st.put(u16(b, 88)); st.put(u16(b, 90)); st.put(u16(b, 92))
            st.put(u16(b, 96)); st.put(u16(b, 98)); st.put(u16(b, 94))
            o.put("stats", st)
        }
        if (u32(b, 80) != 0L) o.put("status", "status")
        return o
    }

    /**
     * Decode one BoxPokemon. CFRU's box struct is NOT the party struct: it drops
     * the vanilla checksum/padding, so the substructures begin at +28 rather
     * than +32. Proven against a live capture — a boxed Inkay read species 794
     * at +28 and exp 1331 at +32, and 1331 is exactly 11^3, i.e. level 11 on
     * the Medium-Fast curve. Reading it at the party's +32 gave species "Deino"
     * and a nonsense level 100, which is how the offset was caught.
     *
     * Box mons carry no level field at all (that lives in the party-only tail),
     * so level is derived from experience. Moves are not at the offset the party
     * layout implies and are left out; they fill in from party sync the moment
     * the mon is withdrawn.
     */
    private fun decodeBoxMon(b: ByteArray, off: Int): JSONObject? {
        if (off + 80 > b.size) return null
        val pers = u32(b, off); val ot = u32(b, off + 4)
        if (pers == 0L && ot == 0L) return null
        val species = u16(b, off + 28)
        if (species !in 1..2999) return null
        val o = JSONObject()
        o.put("species", profile.speciesById[species] ?: "#" + species)
        decodeG3(b, off + 8, 10)?.let { if (it.isNotEmpty()) o.put("nickname", it) }
        val exp = u32(b, off + 32).toInt()
        val growth = profile.growthById[species]
        if (growth != null) {
            var lv = 1
            for (n in 1..100) { if (expAt(growth, n) <= exp) lv = n else break }
            o.put("level", lv)
        }
        val item = u16(b, off + 30)
        o.put("item", if (item in 1..1299) profile.itemsById[item] ?: "" else "")
        // Personality sits at +0 in the box struct exactly as in the party one,
        // so nature costs nothing here — and a boxed mon that reached the roster
        // with a blank nature never got one filled in later.
        o.put("nature", NATURES[(pers % 25).toInt()])
        // Types (and the slot-0 ability) come from the SPECIES tables, not from
        // the box record, so they are exactly as trustworthy here as in the
        // party — unlike moves, which genuinely are not in this record.
        profile.typeBySpecies[species]?.let { if (it.isNotEmpty()) o.put("types", JSONArray(it)) }
        // NO ability for boxed mons. The species table gives both candidates but
        // NOT which one this individual has — that is the abilityNum bit, and it
        // lives in the part of the box record that reads as zeros. Sending
        // slot 0 regardless was a guess that got it wrong exactly when the mon
        // has its second ability (a Riolu read "Steadfast" while the game said
        // "Inner Focus"), and because the tracker would not overwrite an ability
        // it already had, the wrong value then survived being withdrawn.
        // Ability resolves properly from the party read instead.
        // NO ability slot and NO moves for boxed mons, deliberately.
        // Species (+28) and exp (+32) are confirmed against a live capture, but
        // the rest of the record is not what the party layout implies: a
        // known-plaintext search for EVERY move in the mon's learnset — plain and
        // XOR-decrypted, across the whole 80-byte slot — found nothing, and bytes
        // 64..79 read as all zeros, which is also where the ability bit would
        // live. So CFRU's box record either runs longer than 80 bytes or keeps
        // these elsewhere. Emitting a guess would put wrong moves and a wrong
        // ability on the roster; both populate correctly from party sync the
        // moment the mon is withdrawn.
        o.put("boxed", true)
        return o
    }

    private fun pollOnce(sock: DatagramSocket, addr: InetAddress) {
        val a = profile.addrs
        // Route via current map header's regionMapSectionId.
        var route: String? = null
        read(sock, addr, a.gMapHeader, 0x18)?.let { hdr ->
            if (hdr.size > a.sectionIdOff) route = profile.sectionNames[hdr[a.sectionIdOff].toInt() and 0xFF]
        }
        // Party.
        val party = JSONArray()
        val count = read(sock, addr, a.partyCount, 1)?.let { it[0].toInt() and 0xFF } ?: 0
        val playerSlots = readParty(sock, addr, a.playerParty, minOf(count, 6))
        for (b in playerSlots) decodeMon(b)?.let { party.put(it) }
        // Encounter, gated by the exact in-battle flag.
        var encounter: JSONObject? = null
        // Leaving battle needs CONSECUTIVE negative reads, and a FAILED read holds the
        // previous state rather than reporting "not in battle".
        //
        // Both matter. Field report on Lazarus: the tracker flashed the route view for a
        // frame mid-attack and then returned to the battle. With no hysteresis a single
        // zero — whether the flag genuinely dips during an animation or a UDP read is
        // simply dropped — rewrote the whole payload to the overworld, and the next poll
        // rewrote it back. `?: false` was the worse half: a lost packet is not evidence
        // that the battle ended, but it was being treated as exactly that.
        val rawInBattle = read(sock, addr, a.inBattle, 1)?.let { it[0].toInt() != 0 }
        val inBattle = when {
            rawInBattle == true -> { battleFalseStreak = 0; true }
            rawInBattle == null -> inBattleNow                    // read failed: hold
            else -> {
                battleFalseStreak++
                if (battleFalseStreak >= BATTLE_EXIT_READS) false else inBattleNow
            }
        }
        inBattleNow = inBattle
        // gBattlerPartyIndexes is u16[4]: battlers 0/2 are YOUR side, 1/3 the
        // opponent's. [0] already drove our own active-mon focus; [1] is the
        // foe's active party slot, so reading it makes the tracker follow a
        // TRAINER's switches the same way (verified layout: a user snapshot
        // showed [0] tracking the player's switch to slot 4, [1]=0 in singles).
        var mySlot = -1
        var mySlot2 = -1
        var foeSlot = 0
        var foe2Slot = 1
        if (inBattle && a.battlerIndexes != 0L) {
            read(sock, addr, a.battlerIndexes, 8)?.let { bi ->
                // [0] you, [1] them, [2] YOUR second (doubles), [3] their second.
                // [2] was skipped, so in a double battle the tracker only ever
                // knew about one of your two mons on the field.
                val s0 = u16(bi, 0); val s1 = u16(bi, 2)
                val s2 = u16(bi, 4); val s3 = u16(bi, 6)
                if (s0 in 0..5) mySlot = s0
                if (s1 in 0..5) foeSlot = s1
                if (s2 in 0..5) mySlot2 = s2
                if (s3 in 0..5) foe2Slot = s3
            }
        }
        // Fallback for profiles with no gBattlerPartyIndexes (Lazarus, TRE Johto):
        // focus the first party member that still has HP. Without this mySlot stays -1
        // and the active-mon block below never runs at all, so the tracker shows NOBODY
        // on the field for those games.
        //
        // This is a heuristic and is deliberately only used when the real address is
        // absent. It is right whenever the lead is out or a faint forced the switch, and
        // WRONG if the player switched past a healthy Pokemon — that case needs the real
        // gBattlerPartyIndexes, which only a live probe can locate.
        if (inBattle && mySlot < 0) {
            for (i in 0 until party.length()) {
                if (party.getJSONObject(i).optInt("hp", 0) > 0) { mySlot = i; break }
            }
        }
        // Wild vs trainer, from gBattleTypeFlags: 0x1 DOUBLE, 0x4 IS_MASTER,
        // 0x8 TRAINER. All confirmed against live Thor snapshots: wild singles
        // read 0x4, a trainer single read 0xc (IS_MASTER|TRAINER), and a trainer
        // DOUBLE read 0x20000d (DOUBLE|IS_MASTER|TRAINER + a CFRU flag at
        // 0x200000). That last one is why the gate can NOT require the value to
        // fit in 16 bits — CFRU/Unbound sets bits well above the vanilla range,
        // and the old "v < 0x10000" check threw the real double battle away,
        // reporting it as a wild single. Gate on IS_MASTER plus obvious-garbage
        // rejection instead; we only read this while inBattle is already true.
        var kind = "wild"
        var kindKnown = false
        var isDouble = false
        if (inBattle && a.battleTypeFlags != 0L) {
            read(sock, addr, a.battleTypeFlags, 4)?.let { fb ->
                val bk = battleKind(u32(fb, 0))
                if (bk.known) { kindKnown = true; if (bk.trainer) kind = "trainer"; isDouble = bk.double }
            }
        }
        // gBattlersCount is an INDEPENDENT read of the same fact: 2 in a single
        // battle, 4 in a double (both verified from device snapshots). Doubles
        // detection previously rested entirely on one flag bit, and when that
        // bit was misread the whole feature silently degraded — so cross-check
        // it here. Either signal saying "4 battlers" is enough.
        // Whose action the game is asking for RIGHT NOW. gBattleControllerExecFlags
        // is a bitmask — bit N set means battler N's controller is the one being
        // waited on. Battlers 0/2 are yours, 1/3 theirs. Pinned from five labelled
        // captures of one double battle: 0x1 across all three captures taken while
        // the LEFT mon was choosing, 0x4 for the RIGHT mon, with every other byte
        // in the battle-globals block identical. (gActiveBattler is NOT usable for
        // this — it churns as controllers run and is never stable at capture time.)
        var choosingBattler = -1
        if (inBattle && a.execFlags != 0L) {
            read(sock, addr, a.execFlags, 4)?.let { fb ->
                val v = u32(fb, 0)
                for (bit in 0 until 4) if ((v and (1L shl bit)) != 0L) { choosingBattler = bit; break }
            }
        }
        // Target-selection cursor: the battler id being aimed at — 1 or 3 on the
        // opposing side. NOTE those ids are the OPPONENT's own left/right, which
        // is mirrored on screen: 1 appears on your RIGHT, 3 on your LEFT.
        var targetBattler = -1
        var targetRaw = -1
        if (inBattle && a.targetCursor != 0L) {
            read(sock, addr, a.targetCursor, 1)?.let { tc ->
                targetRaw = tc[0].toInt() and 0xFF
                if (targetRaw == 1 || targetRaw == 3) targetBattler = targetRaw
            }
        }
        if (inBattle && a.battlersCount != 0L) {
            read(sock, addr, a.battlersCount, 1)?.let { bc ->
                val n = bc[0].toInt() and 0xFF
                if (n == 4) isDouble = true
                if (n == 2 || n == 4) kindKnown = kindKnown || false
            }
        }
        if (inBattle) {
            val enemySlots = readParty(sock, addr, a.enemyParty, 6)
            decodeMon(enemySlots.getOrNull(foeSlot))?.let { e ->
                if (e.optInt("maxHp") > 0 && e.optInt("level") in 1..100) {
                    e.put("kind", kind)
                    // Only a real DOUBLE battle has a second foe on the field.
                    // The old slot-1 heuristic reported a trainer's benched
                    // second Pokémon as a "doubles partner"; with the flags
                    // known we can tell the difference. Flags unknown → keep the
                    // old heuristic so nothing regresses on unverified profiles.
                    val partnerSlot = if (kindKnown) foe2Slot else 1
                    val wantPartner = if (kindKnown) isDouble else true
                    if (wantPartner && partnerSlot != foeSlot)
                    decodeMon(enemySlots.getOrNull(partnerSlot))?.let { p ->
                        if (p.optInt("maxHp") > 0 && p.optInt("level") in 1..100) {
                            val po = JSONObject(); po.put("species", p.optString("species")); po.put("level", p.optInt("level"))
                            e.put("partner", po)
                        }
                    }
                    // The opponent's WHOLE party. Gating the doubles partner on
                    // BATTLE_TYPE_DOUBLE fixed a wrong "partner" readout but took
                    // away the only view of a trainer's bench — and the moment you
                    // most need it is "X is about to send out Y", deciding whether
                    // to stay in. Slots that don't decode are simply absent, so a
                    // wild battle yields a single-entry list.
                    val team = JSONArray()
                    // Do NOT assume the enemy party is contiguous. A two-trainer
                    // double lays each trainer's mons out in its own sub-range,
                    // so a real battle read slots 0,1,3,4 with a HOLE at 2 — the
                    // old stop-at-first-empty scan quit there and never saw the
                    // second trainer's Pokémon at all. Skip empties, don't stop.
                    for (s in 0 until 6) {
                        val tm = decodeMon(enemySlots.getOrNull(s)) ?: continue
                        if (tm.optInt("maxHp") <= 0 || tm.optInt("level") !in 1..100) continue
                        val to = JSONObject()
                        to.put("species", tm.optString("species"))
                        to.put("level", tm.optInt("level"))
                        to.put("hp", tm.optInt("hp"))
                        to.put("maxHp", tm.optInt("maxHp"))
                        // Their actual moveset, straight out of the same struct
                        // layout as the player's party. Knowing what a foe can
                        // DO matters more than its stats — a mon you switch in
                        // with two super-effective attacks is still a bad trade
                        // if it eats a super-effective hit first.
                        tm.optJSONArray("moves")?.let { to.put("moves", it) }
                        tm.optString("item").takeIf { it.isNotEmpty() }?.let { to.put("item", it) }
                        // In doubles TWO of them are out; marking only foeSlot
                        // made the second on-field foe look like a bench mon
                        // (and the tracker then offered to "scout" something
                        // already staring at you).
                        to.put("slot", s)
                        // Battler position, so the tracker can order/label these
                        // the way the SCREEN does. Gen-3 names positions from
                        // each side's own perspective, so OPPONENT_LEFT (1)
                        // actually renders on the PLAYER'S RIGHT and
                        // OPPONENT_RIGHT (3) on the player's left — confirmed
                        // in game. Everything keyed off identity (party slot)
                        // was already correct; only the left/right labelling
                        // was inverted.
                        // Ordering hint only (no left/right claim is made in the
                        // UI any more). Kept consistent with the target mapping
                        // above so the columns and the focus agree.
                        if (isDouble && s == foe2Slot) to.put("pos", 1)
                        else if (s == foeSlot) to.put("pos", 3)
                        to.put("active", s == foeSlot || (isDouble && s == foe2Slot))
                        team.put(to)
                    }
                    if (team.length() > 0) e.put("team", team)
                    // Which foe your cursor is currently on (party slot, matching
                    // the "slot" field on each team entry).
                    if (targetBattler >= 0 && isDouble) {
                        // Cursor value -> which foe. Determined by OBSERVATION,
                        // not by reasoning about position constants: mapping 1 to
                        // gBattlerPartyIndexes[1] put the focus on the other foe
                        // every time, confirmed on device across several battles.
                        // Whatever the cursor is indexing, it is not that array in
                        // the order assumed, so the pairing is taken from what the
                        // game actually does. Two attempts to derive this from
                        // B_POSITION_* naming both came out backwards.
                        e.put("targetSlot", if (targetBattler == 1) foe2Slot else foeSlot)
                    }
                    e.remove("hp"); e.remove("maxHp"); e.remove("status")
                    encounter = e
                }
            }
        }

        // Game clock (raw RTC struct; Time Turner offset TBD — see profile note).
        var timeOfDay: String? = null
        if (a.gameHour != 0L) read(sock, addr, a.gameHour, 1)?.let { hb ->
            val hour = hb[0].toInt() and 0xFF
            if (hour in 0..23) timeOfDay = if (hour in 6..19) "day" else "night"
        }
        // Sweep one PC box per poll while out of battle. Catches made with a
        // full party go straight to storage and never touch the party struct,
        // so without this they are invisible to the tracker entirely.
        if (!inBattle && a.storagePtr != 0L) {
            read(sock, addr, a.storagePtr, 4)?.let { pb ->
                val storage = u32(pb, 0)
                if (storage > 0x02000000L && storage < 0x03000000L) {
                    val boxBase = storage + 4 + boxCursor.toLong() * 30L * 80L
                    val blk = ByteArray(2400)
                    var ok = true
                    for (chunk in 0 until 3) {
                        val part = read(sock, addr, boxBase + chunk * 800L, 800)
                        if (part == null || part.size < 800) { ok = false; break }
                        System.arraycopy(part, 0, blk, chunk * 800, 800)
                    }
                    if (ok) {
                        val list = mutableListOf<JSONObject>()
                        for (slot in 0 until 30) decodeBoxMon(blk, slot * 80)?.let { list.add(it) }
                        boxContents[boxCursor] = list
                        boxSweptAt[boxCursor] = System.currentTimeMillis()
                    } else {
                        // Could not confirm this box — drop what we think we know
                        // rather than keep serving it. A cached box is the one
                        // piece of state that outlives everything short of a
                        // restart, so an unconfirmed entry is exactly the kind of
                        // thing that lingers as a phantom.
                        boxContents[boxCursor] = mutableListOf()
                        boxSweptAt[boxCursor] = 0L
                    }
                    boxCursor = (boxCursor + 1) % 14
                }
            }
        }
        // Sanity-check the read against the loaded profile. Every address here
        // is per-GAME, so pointing the wrong profile at a running game decodes
        // cleanly-shaped nonsense — a plausible party count, species ids that
        // resolve to the wrong names or to "#1234" placeholders — with nothing
        // upstream looking broken. That is indistinguishable from a bug unless
        // it is called out, so say it here rather than let it read as live truth.
        run {
            val placeholders = (0 until party.length()).count {
                party.getJSONObject(it).optString("species").startsWith("#")
            }
            val bad = count > 6 || (party.length() > 0 && placeholders * 2 >= party.length())
            if (bad) {
                lastError = "Profile may not match the running game — " +
                    "party reads $count with $placeholders unnamed species. " +
                    "Check the Game selection above matches what is loaded."
            } else if (lastError.startsWith("Profile may not match")) {
                lastError = "—"
            }
        }
        BridgeCore.lastMemoryPollAt = System.currentTimeMillis()
        val state = JSONObject()
        state.put("type", "state")
        state.put("source", "memory")
        state.put("game", profile.game)
        // Active battler → allies signal: the tracker's existing "Your moves"
        // auto-select follows whoever is actually on the field (switch-aware —
        // gBattlerPartyIndexes[0] verified via user RAM snapshot).
        if (inBattle && mySlot in 0 until party.length()) {
            val allies = JSONArray()
            allies.put(party.getJSONObject(mySlot).optString("species"))
            // Doubles: your partner slot is on the field too, so it belongs in
            // the allies list the battle panel matches against.
            if (isDouble && mySlot2 in 0 until party.length() && mySlot2 != mySlot) {
                allies.put(party.getJSONObject(mySlot2).optString("species"))
            }
            state.put("allies", allies)
        }
        // The mon whose move you are picking — the tracker focuses it so the
        // move list always belongs to whoever the game is asking about.
        if (choosingBattler == 0 || choosingBattler == 2) {
            val slot = if (choosingBattler == 0) mySlot else mySlot2
            if (slot in 0 until party.length()) {
                state.put("choosing", party.getJSONObject(slot).optString("species"))
            }
        }
        run {
            // Only report boxes confirmed RECENTLY. The rotation covers all 14
            // in about 14 seconds, so anything older than a minute means the
            // sweep stalled — and stale box contents are worse than none, since
            // the tracker treats an unknown mon as a real catch and adds it to
            // the run. Loading a savestate is the case that bites: the world
            // changes wholesale while the cache still describes the old one.
            val fresh = System.currentTimeMillis() - 60000
            val boxArr = JSONArray()
            for (i in boxContents.indices) if (boxSweptAt[i] > fresh) for (m in boxContents[i]) boxArr.put(m)
            if (boxArr.length() > 0) state.put("box", boxArr)
        }
        if (route != null) state.put("route", route)
        if (timeOfDay != null) state.put("timeOfDay", timeOfDay)
        state.put("party", party)
        state.put("encounter", encounter ?: JSONObject.NULL)
        val cmp = state.toString()
        lastStateSummary = buildString {
            append('[').append(profile.game).append("] ")
            append(route ?: "?")
            append(" · party ").append(party.length())
            encounter?.let { append(" · vs ").append(it.optString("species")).append(" [").append(kind).append("]") }
            // Live readout of the two cursors, so a mis-pinned address is
            // visible on this screen instead of needing another snapshot round
            // trip: watch "turn" change as the game asks each of your mons, and
            // "tgt" change as you move the target cursor.
            if (inBattle) {
                append(" · turn=").append(if (choosingBattler >= 0) choosingBattler.toString() else "?")
                append(" tgt=").append(if (targetRaw >= 0) targetRaw.toString() else "?")
            }
        }
        // Broadcast on CHANGE, or on a heartbeat if nothing has changed for a
        // while. Change-only emission meant a player standing still sent no
        // frames at all, which is indistinguishable from a dead feed — the
        // tracker's staleness warning fired on a perfectly healthy bridge and
        // only cleared when something moved. A floor interval keeps the feed
        // demonstrably alive without making it chatty: on loopback this is a few
        // hundred bytes every couple of seconds.
        val now = System.currentTimeMillis()
        val heartbeat = now - lastBroadcastAt >= HEARTBEAT_MS
        if (cmp != lastJson || heartbeat) {
            lastBroadcastAt = now
            lastJson = cmp
            state.put("ts", System.currentTimeMillis())
            BridgeCore.lastState = state
            BridgeCore.lastEmit = state.toString()
            BridgeCore.server?.broadcastState(state)
            BridgeCore.notifyChanged()
        }
    }

    companion object {
        /** Negative reads required before the bridge accepts that a battle ended.
         *  At the 400 ms in-battle poll this costs under a second of latency on a real
         *  battle end, and absorbs the single-frame dips that were flashing the route. */
        private const val BATTLE_EXIT_READS = 2

        val NATURES = listOf(
            "Hardy","Lonely","Brave","Adamant","Naughty","Bold","Docile","Relaxed","Impish","Lax",
            "Timid","Hasty","Serious","Jolly","Naive","Modest","Mild","Quiet","Bashful","Rash",
            "Calm","Gentle","Sassy","Careful","Quirky")
        // Total exp at level n per Gen-3 growth enum (0 MedFast,1 Erratic,
        // 2 Fluctuating,3 MedSlow,4 Fast,5 Slow). Integer math as the game does.
        fun expAt(growth: Int, n: Int): Int {
            val n3 = n * n * n
            return when (growth) {
                0 -> n3
                1 -> when {                                   // Erratic
                    n <= 50 -> n3 * (100 - n) / 50
                    n <= 68 -> n3 * (150 - n) / 100
                    n <= 98 -> n3 * ((1911 - 10 * n) / 3) / 500
                    else -> n3 * (160 - n) / 100
                }
                2 -> when {                                   // Fluctuating
                    n <= 15 -> n3 * (((n + 1) / 3) + 24) / 50
                    n <= 36 -> n3 * (n + 14) / 50
                    else -> n3 * ((n / 2) + 32) / 50
                }
                3 -> 6 * n3 / 5 - 15 * n * n + 100 * n - 140  // Medium Slow
                4 -> 4 * n3 / 5                               // Fast
                else -> 5 * n3 / 4                            // Slow
            }
        }
        /** Decoded gBattleTypeFlags. */
        data class BattleKind(val known: Boolean, val trainer: Boolean, val double: Boolean)
        /**
         * gBattleTypeFlags → what kind of battle this is. Bits: 0x1 DOUBLE,
         * 0x4 IS_MASTER, 0x8 TRAINER. Values observed live on the Thor:
         *   0x4        wild single
         *   0xc        trainer single
         *   0x20000d   trainer DOUBLE (+ a CFRU flag at 0x200000)
         * The high bit in that last one is why we must NOT require the value to
         * fit in 16 bits — an earlier version did, rejected the real double
         * battle, and reported it as a wild single.
         */
        fun battleKind(v: Long): BattleKind =
            if ((v and 0x4L) != 0L && v != 0xFFFFFFFFL)
                BattleKind(true, (v and 0x8L) != 0L, (v and 0x1L) != 0L)
            else BattleKind(false, false, false)

        /**
         * Gen-3 in-game text → ASCII. Same table the desktop tooling uses:
         * 0x00 space, 0xA1.. digits, 0xBB.. A-Z, 0xD5.. a-z, 0xFF terminator.
         * Returns null if it hits a byte outside the set, so a garbled read
         * yields nothing rather than mojibake.
         */
        fun decodeG3(b: ByteArray, off: Int, max: Int): String? {
            val sb = StringBuilder()
            for (i in 0 until max) {
                if (off + i >= b.size) break
                val c = b[off + i].toInt() and 0xFF
                when {
                    c == 0xFF -> return sb.toString().trim()
                    c == 0x00 -> sb.append(' ')
                    c in 0xBB..0xD4 -> sb.append(('A' + (c - 0xBB)))
                    c in 0xD5..0xEE -> sb.append(('a' + (c - 0xD5)))
                    c in 0xA1..0xAA -> sb.append(('0' + (c - 0xA1)))
                    c == 0xAD -> sb.append('.')
                    c == 0xAE -> sb.append('-')
                    c == 0xB4 -> sb.append(0x27.toChar())
                    c == 0xB5 -> sb.append('♂')
                    c == 0xB6 -> sb.append('♀')
                    else -> return null
                }
            }
            return sb.toString().trim()
        }

        /**
         * Re-send unchanged state at least this often. Comfortably inside the
         * tracker's 8 s staleness threshold, so two beats can be lost before it
         * warns — enough tolerance that a single slow poll is not reported as a
         * failure, while a genuinely dead feed still surfaces quickly.
         */
        private const val HEARTBEAT_MS = 2500L

        private val ORDERS = listOf(
            "GAEM","GAME","GEAM","GEMA","GMAE","GMEA","AGEM","AGME","AEGM","AEMG","AMGE","AMEG",
            "EGAM","EGMA","EAGM","EAMG","EMGA","EMAG","MGAE","MGEA","MAGE","MAEG","MEGA","MEAG"
        )
    }
}

/** Loaded from assets/memory/<game>.json (dump-memory-profile.mjs output). */
class MemoryProfile(json: JSONObject) {
    val game: String = json.optString("game", "unbound")
    val addrs = Addrs(json.getJSONObject("addrs"))
    val speciesById: Map<Int, String> = json.getJSONObject("speciesById").let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    val sectionNames: Map<Int, String> = json.getJSONObject("sectionNames").let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    val growthById: Map<Int, Int> = (json.optJSONObject("growthById") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getInt(it) }
    }
    val movesById: Map<Int, String> = (json.optJSONObject("movesById") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    val itemsById: Map<Int, String> = (json.optJSONObject("itemsById") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    /** species id → [type1, type2], dumped from the ROM's own tables. */
    val typeBySpecies: Map<Int, List<String>> = (json.optJSONObject("typeBySpecies") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { k ->
            val arr = o.getJSONArray(k)
            k.toInt() to (0 until arr.length()).map { arr.getString(it) }
        }
    }
    /** species id → ability names by slot, dumped from the ROM's own tables. */
    val abilityBySpecies: Map<Int, List<String>> = (json.optJSONObject("abilityBySpecies") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { k ->
            val arr = o.getJSONArray(k)
            k.toInt() to (0 until arr.length()).map { arr.getString(it) }
        }
    }
    class Addrs(o: JSONObject) {
        val partyCount = o.getLong("partyCount")
        val playerParty = o.getLong("playerParty")
        val enemyParty = o.getLong("enemyParty")
        val gMapHeader = o.getLong("gMapHeader")
        val sectionIdOff = o.getInt("sectionIdOff")
        val inBattle = o.getLong("inBattle")
        val gameHour = o.optLong("gameHour", 0L)
        val battlerIndexes = o.optLong("battlerIndexes", 0L)
        val battleTypeFlags = o.optLong("battleTypeFlags", 0L)
        val battlersCount = o.optLong("battlersCount", 0L)
        val execFlags = o.optLong("execFlags", 0L)
        val targetCursor = o.optLong("targetCursor", 0L)
        val storagePtr = o.optLong("storagePtr", 0L)
    }
}
