package com.runeshift.nuzbridge

import org.json.JSONArray
import org.json.JSONObject
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress
import java.net.SocketTimeoutException

/**
 * RetroArch RAM producer — the high-fidelity path. Polls RetroArch's UDP
 * network-command interface (READ_CORE_MEMORY, port 55355; the user enables
 * Settings ▸ Network ▸ Network Commands in RetroArch) and emits exact game
 * state: species, levels, HP, route, and battle on/off.
 *
 * Direct port of the validated desktop reference (_tools/memory-bridge.mjs).
 * All addresses/tables come from the game's memory profile JSON
 * (assets/memory/<game>.json, generated by _tools/dump-memory-profile.mjs and
 * verified live against RetroArch+mGBA on 2026-08-17: party @0x02024284 with
 * UNENCRYPTED species u16 @+32 (CFRU), enemy @0x0202402C (+100 = doubles
 * partner), gMapHeader section @0x02036DFC+0x14, gMain.inBattle @0x03003529).
 */
class MemoryProducer(private val profile: MemoryProfile) {

    @Volatile var running = false
        private set
    @Volatile var lastError: String = "—"
    @Volatile var lastStateSummary: String = "—"
    @Volatile var readsOk = 0L
    @Volatile var readsFailed = 0L

    private var thread: Thread? = null
    private var lastJson: String? = null
    private var lastBroadcastAt = 0L
    /** Drives the poll interval — see loop(). */
    private val BATTLE_START_READS = 2
    @Volatile private var inBattleNow = false
    /** When the battle flag was last seen high; drives the exit latch below. */
    private var lastBattleSeenAt = 0L
    // PC boxes, swept ONE box per poll rather than all at once: the full
    // storage is 14x30x80 = 33.6 KB, which as a single burst would stall the
    // loop, but a box at a time is ~3 extra reads and covers everything every
    // ~14 s. Cached per box so the emitted list stays complete between sweeps.
    private val boxContents = Array(14) { mutableListOf<JSONObject>() }
    private val boxSweptAt = LongArray(14)
    private var boxCursor = 0

    fun start() {
        if (running) return
        running = true
        thread = Thread({ loop() }, "nuz-memory-producer").apply { isDaemon = true; start() }
    }

    fun stop() {
        running = false
        thread = null
    }

    // The content string this profile was last confirmed against. A cartridge SWAP that
    // resolves to nothing must not be treated the same as a cartridge that was never
    // recognised in the first place.
    @Volatile private var confirmedContent: String? = null

    // Which foe the no-battler-indexes fallback last settled on, so the end of a battle
    // holds that one rather than snapping back to the lead. Cleared when a battle ends so
    // it cannot leak into the next one.
    @Volatile private var lastFoeGuess = 0
    // Consecutive high reads seen so far. A battle STARTING must be corroborated;
    // a battle CONTINUING must not, or every animation frame could end it.
    @Volatile private var highRun = 0

    /**
     * True when this profile cannot be trusted for what is actually running.
     *
     * Two cases, and the second one used to be missed. Detection recognising a DIFFERENT
     * game is obvious. Detection recognising NOTHING is the dangerous one: "unrecognised →
     * trust the user" is right for a ROM that is simply absent from the fingerprint table
     * and was chosen by hand, and catastrophic after a swap — the producer keeps the old
     * profile AND the old game label, reads the new cartridge through the wrong addresses,
     * and emits species that map through the old game's name table. They look native, the
     * tracker's wrong-cartridge check passes, and other games' Pokemon get written into the
     * run. Reported as "it started adding Pokemon from the current game to what was loaded
     * before", which is the one failure here with no undo.
     *
     * So: unrecognised is tolerated only while the content has not changed since this
     * profile was last confirmed against it.
     */
    private fun mismatched(): Boolean {
        val d = GameDetect.lastGame
        if (d != null) {
            if (d == profile.game) { confirmedContent = GameDetect.lastContent; return false }
            return true
        }
        val now = GameDetect.lastContent ?: return false          // nothing detected at all yet
        val was = confirmedContent
        if (was == null) { confirmedContent = now; return false }  // never recognised — user's choice
        return now != was                                          // swapped into something unknown
    }

    private fun loop() {
        var sock = DatagramSocket().apply { soTimeout = 800 }
        val addr = InetAddress.getByName("127.0.0.1")
        var deadPolls = 0
        var ticks = 0L
        try {
            while (running) {
                val okBefore = readsOk
                // Check the cartridge before the first poll, then every ~10 s.
                // Doing it first matters: otherwise the opening poll of a
                // freshly-switched game emits a full wrong-profile roster
                // before detection ever runs.
                // Every ~10s normally, but IMMEDIATELY whenever reads are failing. A
                // cartridge swap looks exactly like reads failing — the old profile's
                // addresses stop returning anything sensible — so waiting out the rest of
                // the interval is the one time the answer is already known. That delay is
                // the lag between changing games and the tracker noticing.
                // Every ~3 polls, not 10. A swap frequently does NOT fail reads — the new
                // ROM answers at the old addresses with meaningless data — so deadPolls
                // stays 0 and the old ten-second interval was the whole delay between
                // changing cartridges and anything noticing. One GET_STATUS packet is
                // nothing next to the ~11 memory reads each poll already sends.
                if (ticks == 0L || ticks % 3L == 0L || deadPolls > 0) {
                    try { detectGame(sock, addr) } catch (e: Throwable) { /* best-effort */ }
                }
                ticks++
                if (mismatched()) {
                    // Wrong profile for the running game: emit NOTHING. A wrong
                    // roster is worse than no roster — it writes other games'
                    // Pokemon into the run and there is no undo for that.
                    lastError = if (GameDetect.lastGame != null)
                        "Wrong profile — RetroArch is running ${GameDetect.lastGame} " +
                        "but this is ${profile.game}. Switching…"
                    else
                        "Unrecognised cartridge (${GameDetect.lastContent}) — paused rather than " +
                        "read it through ${profile.game}'s addresses."
                    lastStateSummary = "[${profile.game}] paused — wrong game loaded"
                    Thread.sleep(1000L)
                    continue
                }
                try { pollOnce(sock, addr) } catch (e: Throwable) {
                    readsFailed++
                    lastError = "poll: ${e.message ?: e.javaClass.simpleName}"
                }
                if (readsOk > okBefore) {
                    deadPolls = 0
                    // Clear a stale failure message once reads are landing again.
                    // lastError was previously write-only, so a single transient
                    // timeout left "RetroArch not responding" on screen forever
                    // while data was visibly flowing — reported as "says live and
                    // I can see memory data, but also shows the not-connected
                    // error". Only clear messages WE own; a profile-mismatch
                    // warning is still true regardless of read health.
                    if (lastError.startsWith("RetroArch not responding") ||
                        lastError.startsWith("read: ") || lastError.startsWith("poll: ")) {
                        lastError = "—"
                    }
                } else {
                    deadPolls++
                }
                // Nothing at all got through for several polls: assume the socket
                // itself is poisoned and replace it. This is precisely what
                // toggling the memory switch by hand was doing.
                if (deadPolls >= 3) {
                    runCatching { sock.close() }
                    sock = try { DatagramSocket().apply { soTimeout = 800 } } catch (e: Exception) { sock }
                    deadPolls = 0
                    lastError = "socket reset — reconnecting to RetroArch"
                }
                // In battle the interesting state is TRANSIENT: the target-select
                // screen is frequently open for well under a second, so a 1 Hz
                // poll walks straight past it and the panel never sees the cursor
                // move (field report: turn focus followed, target focus didn't).
                // Overworld state changes at walking pace, so keep 1 Hz there.
                Thread.sleep(if (inBattleNow) 400L else 1000L)
            }
        } finally {
            runCatching { sock.close() }
        }
    }

    /**
     * Ask RetroArch what it is running. One packet, every few seconds — cheap
     * next to the ~11 reads a poll already costs, and it is the only thing in
     * the loop that can catch "the profile is decoding the wrong cartridge".
     */
    private fun detectGame(sock: DatagramSocket, addr: InetAddress) {
        val ctx = BridgeCore.appContext ?: return
        val out = "GET_STATUS".toByteArray()
        val buf = ByteArray(512)
        val pkt = DatagramPacket(buf, buf.size)
        val reply = try {
            sock.send(DatagramPacket(out, out.size, addr, 55355))
            sock.receive(pkt)
            String(pkt.data, 0, pkt.length)
        } catch (e: Exception) { return }   // detection is best-effort, never fatal
        if (!reply.startsWith("GET_STATUS")) return
        val r = GameDetect.parse(ctx, reply)
        val changed = GameDetect.record(r)
        // A recognised game that is not the one we are decoding means every
        // number this producer is about to emit is wrong. Hand it to BridgeCore,
        // which owns profile loading and the tracker socket.
        if (r.game != null && r.game != profile.game) BridgeCore.onGameDetected(r.game)
        // Every other CHANGE still has to reach the tracker: a cartridge that resolves to
        // nothing, or back to the one already loaded. Only a switch was being announced, so
        // the app went on naming the previous game and simply went stale when the frames
        // stopped — no way to tell "paused, wrong cartridge" from "the feed died".
        else if (changed) BridgeCore.announceDetection()
    }

    private fun read(sock: DatagramSocket, addr: InetAddress, at: Long, len: Int): ByteArray? {
        val cmd = "READ_CORE_MEMORY ${at.toString(16)} $len"
        val out = cmd.toByteArray()
        val buf = ByteArray(16 + len * 3 + 32)
        val pkt = DatagramPacket(buf, buf.size)
        // The SEND has to be inside the try as well. If RetroArch is momentarily
        // gone — which is exactly what a savestate load looks like — the socket
        // takes an ICMP port-unreachable and Java then throws
        // PortUnreachableException, NOT a timeout. That escaped this function,
        // aborted the whole poll before anything could be broadcast, and kept
        // throwing on the same socket forever: the feed went silent permanently
        // and only creating a new socket (toggling the memory switch) revived it.
        return try {
            sock.send(DatagramPacket(out, out.size, addr, 55355))
            sock.receive(pkt)
            val parts = String(pkt.data, 0, pkt.length).trim().split(" ")
            if (parts.size < 3 || parts[0] != "READ_CORE_MEMORY" || parts[2] == "-1") { readsFailed++; null }
            else {
                readsOk++
                ByteArray(parts.size - 2) { i -> parts[i + 2].toInt(16).toByte() }
            }
        } catch (e: SocketTimeoutException) {
            readsFailed++
            lastError = "RetroArch not responding on :55355 — enable Network Commands"
            null
        } catch (e: Exception) {
            // Any other socket fault: report it and let the loop decide whether
            // the socket needs replacing. Never let it escape the poll.
            readsFailed++
            lastError = "read: ${e.javaClass.simpleName}"
            null
        }
    }

    /**
     * Read a whole party (count x 100 bytes) in ONE request instead of one per
     * slot. Poll cost had crept to ~22 UDP round trips per tick, and at the
     * faster in-battle cadence that saturated the link — every read carries an
     * 800 ms timeout, so a few slow ones stall the entire poll and the battle
     * never appears. Batching takes a double battle from ~22 reads to ~11,
     * fewer than before the cursor work was added.
     *
     * Falls back to per-slot reads if the bulk response comes back short, so a
     * stricter RetroArch build degrades in speed rather than breaking.
     */
    private fun readParty(sock: DatagramSocket, addr: InetAddress, base: Long, count: Int): List<ByteArray?> {
        if (count <= 0) return emptyList()
        val want = count * 100
        val blk = read(sock, addr, base, want)
        if (blk != null && blk.size >= want) {
            return (0 until count).map { blk.copyOfRange(it * 100, it * 100 + 100) }
        }
        return (0 until count).map { read(sock, addr, base + it * 100L, 100) }
    }

    private fun u16(b: ByteArray, o: Int) = ((b[o].toInt() and 0xFF)) or ((b[o + 1].toInt() and 0xFF) shl 8)
    private fun u32(b: ByteArray, o: Int) =
        ((b[o].toInt() and 0xFF).toLong()) or ((b[o + 1].toInt() and 0xFF).toLong() shl 8) or
        ((b[o + 2].toInt() and 0xFF).toLong() shl 16) or ((b[o + 3].toInt() and 0xFF).toLong() shl 24)

    /** Gen-3 party mon → (speciesName, level, hp, maxHp, status) or null. */
    fun decodeMon(b: ByteArray?): JSONObject? {
        if (b == null || b.size < 100) return null
        val personality = u32(b, 0)
        val otId = u32(b, 4)
        if (personality == 0L && otId == 0L) return null
        // Which layout this is gets DECIDED, not guessed. Two exist: CFRU keeps the
        // substructures in the clear with species as a u16 at +32, vanilla Gen-3 encrypts
        // them and shuffles their order by personality.
        //
        // The old test was "is the value at +32 a plausible species id, and if not,
        // decrypt". On an encrypted mon that field is ciphertext, and ciphertext lands in
        // 1..2999 about one time in twenty — at which point a real Pokemon is reported as
        // an entirely different one. A wild Toxexot came through as Petripa, a species
        // that lives two regions away at level 49, and the tracker correctly said it could
        // not be from that route.
        //
        // Gen 3 ships the answer: +28 holds a checksum over the 48 substructure bytes,
        // summed as u16s. Decrypt, sum, compare. It matches only for a genuinely encrypted
        // mon, so there is no guessing left — and it costs one pass over 48 bytes.
        val key = personality xor otId
        val order = ORDERS[(personality % 24).toInt()]
        val gOff = 32 + order.indexOf('G') * 12
        var sum = 0
        for (i in 0 until 12) {
            val w = (u32(b, 32 + i * 4) xor key)
            sum = (sum + (w and 0xFFFF).toInt() + ((w ushr 16) and 0xFFFF).toInt()) and 0xFFFF
        }
        val encrypted = sum == u16(b, 28)
        var species = if (encrypted) ((u32(b, gOff) xor key) and 0xFFFF).toInt() else u16(b, 32)
        // Last resort only: if the checksum says nothing useful (a corrupt or half-written
        // struct), fall back to whichever reading is in range rather than dropping the mon.
        if (species !in 1..2999) species = if (encrypted) u16(b, 32) else ((u32(b, gOff) xor key) and 0xFFFF).toInt()
        if (species !in 1..2999) return null
        // exp lives in the Growth block: CFRU plain u32 @+36 (verified: the
        // captured Lv10 Gible reads 560 = the exact Medium-Slow threshold);
        // encrypted vanilla: Growth word 1 (offset gOff+4, XOR key).
        // Same decision, same answer: read exp from the encrypted Growth block or the plain
        // one. This used to re-derive the layout by comparing +32 against the species it
        // had just chosen, which agreed with the broken test above and so inherited its
        // mistakes.
        var exp = if (encrypted) (u32(b, gOff + 4) xor key).toInt() else u32(b, 36).toInt()
        // Some builds store experience as a u16 at Growth+4 rather than the vanilla u32.
        // Lazarus does: read four bytes there and the upper half belongs to the next
        // field, giving ~534,773,890 instead of 361. That is not merely a wrong number —
        // it lands far past the level-100 threshold, so the EXP bar silently showed
        // nothing. Declared per game via `expWidth` in the profile.
        if (profile.expWidth == 2) exp = exp and 0xFFFF
        val o = JSONObject()
        o.put("species", profile.speciesById[species] ?: "#$species")
        // Nickname: 10 bytes at +8, in the Gen-3 character encoding. Worth
        // having for its own sake, but it also makes roster matching far more
        // reliable than species alone — species collides across duplicates and
        // breaks on regional-form spelling, whereas the nickname is what the
        // player actually recognises the mon by.
        decodeG3(b, 8, 10)?.let { if (it.isNotEmpty()) o.put("nickname", it) }
        // Held item: Growth block u16 @+34 (plain) / word0 high half (encrypted).
        if (profile.itemsById.isNotEmpty()) {
            // `encrypted` decides this, not a comparison against the plaintext field.
            // "+32 disagrees with the species" is only a proxy for encryption, and it fails
            // in exactly the case that matters: when the ciphertext at +32 happens to equal
            // the real species id, the plain path is taken on an encrypted mon.
            var itemId = u16(b, 34)
            if (encrypted) {
                itemId = (((u32(b, gOff) xor key) shr 16) and 0xFFFFL).toInt()
            }
            // Always present when the producer supports items: "" = holding
            // nothing (lets the tracker mirror consumption without ambiguity
            // against older producers that never send the field).
            o.put("item", if (itemId in 1..1299) profile.itemsById[itemId] ?: "" else "")
        }
        val lv = b[84].toInt() and 0xFF
        o.put("level", lv)
        o.put("nature", NATURES[(personality % 25).toInt()])
        profile.growthById[species]?.let { g ->
            if (lv in 1..99) {
                val cur = expAt(g, lv); val next = expAt(g, lv + 1)
                if (next > cur) o.put("expPct", ((exp - cur).coerceIn(0, next - cur)) * 100 / (next - cur))
            } else if (lv == 100) o.put("expPct", 100)
        }
        // Actual moveset: Attacks block (CFRU plain @+44: 4×u16 move ids —
        // verified live: Gible read Tackle/Sand Attack/Metal Claw; encrypted
        // vanilla: A-substructure words). Lets the tracker keep rosters'
        // movesets game-true instead of prompting off learnsets.
        if (profile.movesById.isNotEmpty()) {
            var aOff = 44
            var akey = 0L
            if (encrypted) {
                akey = key
                aOff = 32 + order.indexOf('A') * 12
            }
            val moves = JSONArray()
            for (i in 0 until 4) {
                val raw = if (akey == 0L) u16(b, aOff + i * 2).toLong()
                          else ((u32(b, aOff + (i / 2) * 4) xor akey) shr ((i % 2) * 16)) and 0xFFFFL
                val id = raw.toInt()
                if (id in 1..1399) profile.movesById[id]?.let { moves.put(it) }
            }
            if (moves.length() > 0) o.put("moves", moves)
        }
        // EVs (E-substruct: 6 bytes) and IVs (M-substruct word, 5 bits each).
        // CFRU plain: E @+56, M @+68 (IV word @+72). Game stat order is
        // HP,Atk,Def,SPEED,SpA,SpD — the tracker wants HP,Atk,Def,SpA,SpD,Spe,
        // so slots 3..5 are reordered on the way out.
        run {
            var eOff = 56; var mOff = 68; var xkey = 0L
            if (encrypted) {
                xkey = key
                eOff = 32 + order.indexOf('E') * 12
                mOff = 32 + order.indexOf('M') * 12
            }
            val ge = IntArray(6)
            for (i in 0 until 6) {
                val w = u32(b, eOff + (i / 4) * 4) xor xkey
                ge[i] = ((w shr ((i % 4) * 8)) and 0xFF).toInt()
            }
            // Where this Pokemon was CAUGHT, from the Misc substructure: pokerus at +0,
            // metLocation at +1, originsInfo (metLevel in bits 0-6, then game / ball /
            // OT gender) at +2. The location id indexes the SAME region-map section table
            // the tracker already uses for the current map, so it resolves to a real name
            // for every game without any new data. Nothing game-specific here — it rides
            // on mOff, which is already resolved for both the encrypted and the flat
            // unencrypted layouts.
            val miscWord0 = u32(b, mOff) xor xkey
            val metLocation = ((miscWord0 shr 8) and 0xFFL).toInt()
            val originsInfo = ((miscWord0 shr 16) and 0xFFFFL).toInt()
            val metLevel = originsInfo and 0x7F
            profile.sectionNames[metLocation]?.let { o.put("metLocation", it) }
            if (metLevel in 1..100) o.put("metLevel", metLevel)
            val ivWord = u32(b, mOff + 4) xor xkey
            // Gen-3 packs the ability SLOT into bit 31 of the same word as the
            // IVs (30 bits of IVs + isEgg + abilityNum). We send the slot rather
            // than a name: the tracker already knows each species' ability list,
            // so an index is all it needs and we avoid dragging an ability-name
            // table out of the ROM. NOTE this only distinguishes slots 0 and 1 —
            // a hidden ability needs more than this bit and is not resolved here.
            // WHERE the ability slot lives is not universal. Vanilla Gen 3 packs it into
            // bit 31 of the IV word (30 bits of IVs + isEgg + abilityNum). Lazarus, a
            // pokemon-expansion build, does not: all three party members read 0 there while
            // the game showed Lillipup with Pickup, its SECOND ability. That mon alone has
            // bit 29 of the following (ribbons) word set, and the two whose in-game ability
            // is their first have it clear. Declared per profile rather than sniffed, so no
            // other game changes behaviour.
            val abilitySlot = if (profile.abilitySlotWord2Bit >= 0)
                ((u32(b, mOff + 8) xor xkey) shr profile.abilitySlotWord2Bit and 1L).toInt()
            else ((ivWord shr 31) and 1L).toInt()
            o.put("abilitySlot", abilitySlot)
            // Resolve to a NAME when the profile carries the ROM's ability table.
            // The tracker's own lists are empty for hack-specific species, so
            // sending the name is what makes this work for every mon rather than
            // only the mainline ones.
            profile.abilityBySpecies[species]?.let { list ->
                val pick = list.getOrNull(abilitySlot) ?: list.getOrNull(0)
                if (pick != null) o.put("ability", pick)
            }
            profile.typeBySpecies[species]?.let { types ->
                if (types.isNotEmpty()) o.put("types", JSONArray(types))
            }
            val gi = IntArray(6) { ((ivWord shr (it * 5)) and 0x1F).toInt() }
            val toTracker = { g: IntArray -> intArrayOf(g[0], g[1], g[2], g[4], g[5], g[3]) }
            val evs = toTracker(ge); val ivs = toTracker(gi)
            if (evs.all { it in 0..255 }) o.put("evs", JSONArray(evs.toList()))
            o.put("ivs", JSONArray(ivs.toList()))
        }
        o.put("hp", u16(b, 86))
        o.put("maxHp", u16(b, 88))
        // The cartridge's OWN computed stats live right here in the party
        // struct (+88..98, game order hp,atk,def,SPEED,spAtk,spDef). Sending
        // them lets the tracker DISPLAY what the summary screen shows instead
        // of recomputing it — recomputation drifts by a point whenever an IV
        // is stale or a hack rebalanced a base stat, which is exactly the
        // off-by-one the user reported. Emitted in the tracker's stat order
        // (hp,atk,def,spa,spd,spe).
        run {
            val st = JSONArray()
            st.put(u16(b, 88)); st.put(u16(b, 90)); st.put(u16(b, 92))
            st.put(u16(b, 96)); st.put(u16(b, 98)); st.put(u16(b, 94))
            o.put("stats", st)
        }
        if (u32(b, 80) != 0L) o.put("status", "status")
        return o
    }

    /**
     * Decode one BoxPokemon. CFRU's box struct is NOT the party struct: it drops
     * the vanilla checksum/padding, so the substructures begin at +28 rather
     * than +32. Proven against a live capture — a boxed Inkay read species 794
     * at +28 and exp 1331 at +32, and 1331 is exactly 11^3, i.e. level 11 on
     * the Medium-Fast curve. Reading it at the party's +32 gave species "Deino"
     * and a nonsense level 100, which is how the offset was caught.
     *
     * Box mons carry no level field at all (that lives in the party-only tail),
     * so level is derived from experience. Moves are not at the offset the party
     * layout implies and are left out; they fill in from party sync the moment
     * the mon is withdrawn.
     */
    private fun decodeBoxMon(b: ByteArray, off: Int, stride: Int = 80): JSONObject? {
        // The fields this reads all sit in the first 40 bytes, so the bound is whichever is
        // smaller — a compressed record is shorter than the vanilla one.
        if (off + minOf(40, stride) > b.size) return null
        val pers = u32(b, off); val ot = u32(b, off + 4)
        if (pers == 0L && ot == 0L) return null
        // Same two layouts as a party mon, decided the same way — by the CHECKSUM at +28
        // over the decrypted substructures.
        //
        // Reading species at a fixed +28 is the CFRU shape. In a real Gen-3 box record +28
        // IS that checksum and +32 begins the encrypted substructures, so on a
        // vanilla-layout game this read a checksum as a species id, found it out of range,
        // and returned null for every slot. Twelve of the thirteen profiles that know where
        // storage lives are vanilla-layout, so their PC boxes have been reporting empty —
        // silently, which is why it looked like the feature simply did not fire.
        val key = pers xor ot
        val order = ORDERS[(pers % 24).toInt()]
        val gOff = off + 32 + order.indexOf('G') * 12
        var sum = 0
        var encrypted = false
        if (off + 80 <= b.size) {
            for (i in 0 until 12) {
                val w = (u32(b, off + 32 + i * 4) xor key)
                sum = (sum + (w and 0xFFFF).toInt() + ((w ushr 16) and 0xFFFF).toInt()) and 0xFFFF
            }
            encrypted = sum == u16(b, off + 28)
        }
        // An UNENCRYPTED box record comes in two shapes, and picking the wrong one loses
        // the Pokemon silently rather than reporting it wrongly:
        //   compressed (CFRU, 58-byte slots) — species u16 at +28, exp at +32, item at +30
        //   flat       (Gaia, 80-byte slots) — species u16 at +32, exp at +36, item at +34,
        //                                      i.e. laid out exactly like that game's PARTY
        //                                      record, with +28 left as a zeroed checksum
        // decodeMon already reads +32 for the party, so a game like Gaia had its party read
        // correctly while every boxed mon was dropped: +28 is 0 there, and the range check
        // below turned a real Zigzagoon into an empty slot. Decide by which offset actually
        // resolves to a species this profile knows, rather than assuming one convention.
        var flat = false
        val species = if (encrypted) {
            ((u32(b, gOff) xor key) and 0xFFFF).toInt()
        } else {
            val compressed = u16(b, off + 28)
            if (compressed in 1..2999 && profile.speciesById.containsKey(compressed)) compressed
            else { flat = true; u16(b, off + 32) }
        }
        if (species !in 1..2999) return null
        val o = JSONObject()
        o.put("species", profile.speciesById[species] ?: "#" + species)
        decodeG3(b, off + 8, 10)?.let { if (it.isNotEmpty()) o.put("nickname", it) }
        val exp = if (encrypted) (u32(b, gOff + 4) xor key).toInt() else u32(b, off + if (flat) 36 else 32).toInt()
        val growth = profile.growthById[species]
        if (growth != null) {
            var lv = 1
            for (n in 1..100) { if (expAt(growth, n) <= exp) lv = n else break }
            o.put("level", lv)
        }
        val item = if (encrypted) (((u32(b, gOff) xor key) shr 16) and 0xFFFFL).toInt() else u16(b, off + if (flat) 34 else 30)
        o.put("item", if (item in 1..1299) profile.itemsById[item] ?: "" else "")
        // Personality sits at +0 in the box struct exactly as in the party one,
        // so nature costs nothing here — and a boxed mon that reached the roster
        // with a blank nature never got one filled in later.
        o.put("nature", NATURES[(pers % 25).toInt()])
        // Caught location, same Misc substructure as a party mon. Only where that block
        // actually exists: an encrypted record has it at the personality-ordered offset, a
        // flat unencrypted one at the vanilla +68. A CFRU COMPRESSED record is 58 bytes and
        // has no room for it, so it is skipped rather than read off the end of the slot.
        run {
            val mOff = if (encrypted) off + 32 + order.indexOf('M') * 12
                       else if (flat) off + 68 else -1
            if (mOff >= 0 && mOff + 8 <= b.size) {
                val xk = if (encrypted) key else 0L
                val w0 = u32(b, mOff) xor xk
                val loc = ((w0 shr 8) and 0xFFL).toInt()
                val lvl = (((w0 shr 16) and 0xFFFFL).toInt()) and 0x7F
                profile.sectionNames[loc]?.let { o.put("metLocation", it) }
                if (lvl in 1..100) o.put("metLevel", lvl)
            }
        }
        // Types (and the slot-0 ability) come from the SPECIES tables, not from
        // the box record, so they are exactly as trustworthy here as in the
        // party — unlike moves, which genuinely are not in this record.
        profile.typeBySpecies[species]?.let { if (it.isNotEmpty()) o.put("types", JSONArray(it)) }
        // NO ability for boxed mons. The species table gives both candidates but
        // NOT which one this individual has — that is the abilityNum bit, and it
        // lives in the part of the box record that reads as zeros. Sending
        // slot 0 regardless was a guess that got it wrong exactly when the mon
        // has its second ability (a Riolu read "Steadfast" while the game said
        // "Inner Focus"), and because the tracker would not overwrite an ability
        // it already had, the wrong value then survived being withdrawn.
        // Ability resolves properly from the party read instead.
        // NO ability slot and NO moves for boxed mons, deliberately.
        // Species (+28) and exp (+32) are confirmed against a live capture, but
        // the rest of the record is not what the party layout implies: a
        // known-plaintext search for EVERY move in the mon's learnset — plain and
        // XOR-decrypted, across the whole 80-byte slot — found nothing, and bytes
        // 64..79 read as all zeros, which is also where the ability bit would
        // live. So CFRU's box record either runs longer than 80 bytes or keeps
        // these elsewhere. Emitting a guess would put wrong moves and a wrong
        // ability on the roster; both populate correctly from party sync the
        // moment the mon is withdrawn.
        o.put("boxed", true)
        return o
    }

    private fun pollOnce(sock: DatagramSocket, addr: InetAddress) {
        val a = profile.addrs
        // Route via current map header's regionMapSectionId.
        var route: String? = null
        // The exact map, not just its region name. gMapHeader gives a regionMapSectionId,
        // and several maps deliberately share one — which is why three separate wild tables
        // all present as "BASALIN COAST" and cannot be told apart. gSaveBlock1.location
        // holds the real identity: mapGroup and mapNum at +4/+5.
        var mapId: String? = null
        if (a.saveBlock1Ptr != 0L) {
            read(sock, addr, a.saveBlock1Ptr, 4)?.let { pb ->
                val sb1 = u32(pb, 0)
                if (sb1 > 0x02000000L && sb1 < 0x02040000L) {
                    read(sock, addr, sb1 + 4, 2)?.let { loc ->
                        val g = loc[0].toInt() and 0xFF
                        val m = loc[1].toInt() and 0xFF
                        if (g < 60 && m < 120) mapId = "$g-$m"
                    }
                }
            }
        }
        read(sock, addr, a.gMapHeader, 0x18)?.let { hdr ->
            if (hdr.size > a.sectionIdOff) route = profile.sectionNames[hdr[a.sectionIdOff].toInt() and 0xFF]
        }
        // Some maps carry the WRONG regionMapSectionId in the ROM itself, usually because
        // the hack reused a map from its base game without repointing it. TRE Johto's Five
        // Island Pokemon Center reports section 144, which really is TWO ISLAND — the game
        // is not being misread, it is misinformed. Nothing derived from the section byte
        // can fix that, so mapOverrides keys on the mapGroup-mapNum identity from
        // gSaveBlock1.location, which is unique per map, and replaces the name outright.
        mapId?.let { id -> profile.mapOverrides[id]?.let { route = it } }
        // Movement state. Which encounter POOL you are standing in is not derivable from
        // the map alone — a route with water has a walking table and a surf table, and only
        // the avatar flags say which one you are in. Verified live on TRE Johto: the byte
        // read 0x08 (SURFING, and nothing else) on the water and 0x01 (ON_FOOT) on land,
        // and it was the only byte in a 32-byte window that moved between the two.
        var surfing: Boolean? = null
        if (a.playerAvatar != 0L) {
            read(sock, addr, a.playerAvatar, 1)?.let { av ->
                val f = av[0].toInt() and 0xFF
                // Reject a byte that is claiming everything at once (0xFF is filler, not a
                // state) or claiming nothing — the same guard that would have caught the
                // decompression buffer standing in for inBattle.
                if (f != 0xFF && f != 0x00) surfing = (f and 0x08) != 0
            }
        }
        // Party.
        val party = JSONArray()
        val count = read(sock, addr, a.partyCount, 1)?.let { it[0].toInt() and 0xFF } ?: 0
        val playerSlots = readParty(sock, addr, a.playerParty, minOf(count, 6))
        for (b in playerSlots) decodeMon(b)?.let { party.put(it) }
        // Encounter, gated by the exact in-battle flag.
        var encounter: JSONObject? = null
        // Leaving battle needs CONSECUTIVE negative reads, and a FAILED read holds the
        // previous state rather than reporting "not in battle".
        //
        // Both matter. Field report on Lazarus: the tracker flashed the route view for a
        // frame mid-attack and then returned to the battle. With no hysteresis a single
        // zero — whether the flag genuinely dips during an animation or a UDP read is
        // simply dropped — rewrote the whole payload to the overworld, and the next poll
        // rewrote it back. `?: false` was the worse half: a lost packet is not evidence
        // that the battle ended, but it was being treated as exactly that.
        // ptrHigh profiles read the WHOLE pointer and require it to land inside EWRAM
        // (0x02000000..0x0203FFFF), not merely to start with 0x02. Live capture on Pisces:
        // 0x55555555 at the box screen, 0x02001ab0 in a wild battle. A high-byte-only test
        // would also accept 0x02F00000, which is not a real address — the range check costs
        // nothing here because it is the same round trip.
        val rawInBattle = if (a.inBattlePtrHigh) {
            read(sock, addr, a.inBattle and 0xFFFFFFFCL, 4)?.let {
                val v = u32(it, 0)
                v >= 0x02000000L && v < 0x02040000L
            }
        } else {
            read(sock, addr, a.inBattle, 1)?.let { (it[0].toInt() and a.inBattleMask) != 0 }
        }
        val nowMs = System.currentTimeMillis()
        // Corroborating read: gBattleTypeFlags is loaded when a battle starts. On some
        // games it is cleared on the way out, and where it is, a ZERO here is positive
        // proof the battle is over and we can drop out instantly instead of waiting for
        // the hold to expire. Where it merely retains its last value (TRE Johto does),
        // this never fires and the latch below carries the decision — so reading it is
        // free upside and cannot make the wrong call on its own.
        val typeFlags = if (a.battleTypeFlags != 0L)
            read(sock, addr, a.battleTypeFlags, 4)?.let { u32(it, 0) } else null
        val flagsSayNoBattle = typeFlags == 0L
        if (rawInBattle == true) highRun++ else if (rawInBattle == false) highRun = 0
        val inBattle = when {
            // Rising edge is DEBOUNCED. One high read used to latch the battle on, which
            // is why a decompression transient could pin the tracker in a fight you had
            // already left: heal at a Pokemon Center, talk to an NPC, and the pane snapped
            // back. A real battle stays high for thousands of polls, so demanding two in a
            // row costs at most one poll of latency and rejects every one-shot glitch.
            // Once inBattleNow is set this does not apply — a single high read refreshes.
            rawInBattle == true && (inBattleNow || highRun >= BATTLE_START_READS) ->
                { lastBattleSeenAt = nowMs; true }
            rawInBattle == true -> false                          // high once, not yet trusted
            rawInBattle == null -> inBattleNow                    // read failed: hold
            flagsSayNoBattle -> false                             // corroborated: really over
            // Latched. A low read only ends the battle once the flag has STAYED low for
            // the whole window. Attack-animation dips and in-battle menus (switch, bag,
            // move info) all sit inside it; a real battle end does not, because nothing
            // ever sets the flag high again.
            else -> inBattleNow && (nowMs - lastBattleSeenAt) < profile.battleHoldMs
        }
        if (!inBattle) lastFoeGuess = 0
        inBattleNow = inBattle
        // gBattlerPartyIndexes is u16[4]: battlers 0/2 are YOUR side, 1/3 the
        // opponent's. [0] already drove our own active-mon focus; [1] is the
        // foe's active party slot, so reading it makes the tracker follow a
        // TRAINER's switches the same way (verified layout: a user snapshot
        // showed [0] tracking the player's switch to slot 4, [1]=0 in singles).
        var mySlot = -1
        var mySlot2 = -1
        var foeSlot = 0
        var foe2Slot = 1
        if (inBattle && a.battlerIndexes != 0L) {
            read(sock, addr, a.battlerIndexes, 8)?.let { bi ->
                // [0] you, [1] them, [2] YOUR second (doubles), [3] their second.
                // [2] was skipped, so in a double battle the tracker only ever
                // knew about one of your two mons on the field.
                val s0 = u16(bi, 0); val s1 = u16(bi, 2)
                val s2 = u16(bi, 4); val s3 = u16(bi, 6)
                if (s0 in 0..5) mySlot = s0
                if (s1 in 0..5) foeSlot = s1
                if (s2 in 0..5) mySlot2 = s2
                if (s3 in 0..5) foe2Slot = s3
            }
        }
        // Fallback for profiles with no gBattlerPartyIndexes (Lazarus, TRE Johto):
        // focus the first party member that still has HP. Without this mySlot stays -1
        // and the active-mon block below never runs at all, so the tracker shows NOBODY
        // on the field for those games.
        //
        // This is a heuristic and is deliberately only used when the real address is
        // absent. It is right whenever the lead is out or a faint forced the switch, and
        // WRONG if the player switched past a healthy Pokemon — that case needs the real
        // gBattlerPartyIndexes, which only a live probe can locate.
        if (inBattle && mySlot < 0) {
            for (i in 0 until party.length()) {
                if (party.getJSONObject(i).optInt("hp", 0) > 0) { mySlot = i; break }
            }
        }
        // Wild vs trainer, from gBattleTypeFlags: 0x1 DOUBLE, 0x4 IS_MASTER,
        // 0x8 TRAINER. All confirmed against live Thor snapshots: wild singles
        // read 0x4, a trainer single read 0xc (IS_MASTER|TRAINER), and a trainer
        // DOUBLE read 0x20000d (DOUBLE|IS_MASTER|TRAINER + a CFRU flag at
        // 0x200000). That last one is why the gate can NOT require the value to
        // fit in 16 bits — CFRU/Unbound sets bits well above the vanilla range,
        // and the old "v < 0x10000" check threw the real double battle away,
        // reporting it as a wild single. Gate on IS_MASTER plus obvious-garbage
        // rejection instead; we only read this while inBattle is already true.
        var kind = "wild"
        var kindKnown = false
        var isDouble = false
        // Reuses the value already fetched above for the battle-exit corroboration —
        // this used to be a second read of the same address on every in-battle poll.
        if (inBattle && typeFlags != null) {
            val bk = battleKind(typeFlags)
            if (bk.known) { kindKnown = true; if (bk.trainer) kind = "trainer"; isDouble = bk.double }
        }
        // gBattlersCount is an INDEPENDENT read of the same fact: 2 in a single
        // battle, 4 in a double (both verified from device snapshots). Doubles
        // detection previously rested entirely on one flag bit, and when that
        // bit was misread the whole feature silently degraded — so cross-check
        // it here. Either signal saying "4 battlers" is enough.
        // Whose action the game is asking for RIGHT NOW. gBattleControllerExecFlags
        // is a bitmask — bit N set means battler N's controller is the one being
        // waited on. Battlers 0/2 are yours, 1/3 theirs. Pinned from five labelled
        // captures of one double battle: 0x1 across all three captures taken while
        // the LEFT mon was choosing, 0x4 for the RIGHT mon, with every other byte
        // in the battle-globals block identical. (gActiveBattler is NOT usable for
        // this — it churns as controllers run and is never stable at capture time.)
        var choosingBattler = -1
        if (inBattle && a.execFlags != 0L) {
            read(sock, addr, a.execFlags, 4)?.let { fb ->
                val v = u32(fb, 0)
                for (bit in 0 until 4) if ((v and (1L shl bit)) != 0L) { choosingBattler = bit; break }
            }
        }
        // Target-selection cursor: the battler id being aimed at — 1 or 3 on the
        // opposing side. NOTE those ids are the OPPONENT's own left/right, which
        // is mirrored on screen: 1 appears on your RIGHT, 3 on your LEFT.
        var targetBattler = -1
        var targetRaw = -1
        if (inBattle && a.targetCursor != 0L) {
            read(sock, addr, a.targetCursor, 1)?.let { tc ->
                targetRaw = tc[0].toInt() and 0xFF
                if (targetRaw == 1 || targetRaw == 3) targetBattler = targetRaw
            }
        }
        if (inBattle && a.battlersCount != 0L) {
            read(sock, addr, a.battlersCount, 1)?.let { bc ->
                val n = bc[0].toInt() and 0xFF
                if (n == 4) isDouble = true
                if (n == 2 || n == 4) kindKnown = kindKnown || false
            }
        }
        if (inBattle) {
            val enemySlots = readParty(sock, addr, a.enemyParty, 6)
            // Same fallback the player's side has had, for the foe's. Without
            // gBattlerPartyIndexes foeSlot stays 0 for the whole battle, so when a
            // trainer's lead faints and the next one comes out, the panel goes on showing
            // the CORPSE — reported in TRE Johto: Nidoran at 0/17 still displayed as the
            // active foe while a healthy Koffing was on the field.
            //
            // Only when the real address is absent, and only ever a guess: the first foe
            // with HP left. That is right whenever a faint forced the switch, which is the
            // case that was broken, and wrong if a trainer switches a healthy Pokemon out —
            // which needs the real gBattlerPartyIndexes, and a live probe to find it.
            if (a.battlerIndexes == 0L) {
                val alive = (0 until 6).filter { i ->
                    val m = decodeMon(enemySlots.getOrNull(i))
                    m != null && m.optInt("hp", 0) > 0
                }
                if (alive.isNotEmpty()) {
                    foeSlot = alive[0]
                    lastFoeGuess = foeSlot
                    if (isDouble && alive.size > 1) foe2Slot = alive[1]
                } else {
                    // Every foe down — the trainer is beaten and the battle is running out
                    // its last frames. "First with HP" has no answer here, and falling back
                    // to slot 0 snaps the panel to the trainer's LEAD, which is neither on
                    // the field nor the thing just defeated: reported as "Nidoran sent out"
                    // after the Koffing that replaced it was knocked out. Hold the last foe
                    // actually faced instead.
                    foeSlot = lastFoeGuess
                }
            }
            decodeMon(enemySlots.getOrNull(foeSlot))?.let { e ->
                if (e.optInt("maxHp") > 0 && e.optInt("level") in 1..100) {
                    e.put("kind", kind)
                    // Only a real DOUBLE battle has a second foe on the field.
                    // The old slot-1 heuristic reported a trainer's benched
                    // second Pokémon as a "doubles partner"; with the flags
                    // known we can tell the difference. Flags unknown → keep the
                    // old heuristic so nothing regresses on unverified profiles.
                    val partnerSlot = if (kindKnown) foe2Slot else 1
                    val wantPartner = if (kindKnown) isDouble else true
                    if (wantPartner && partnerSlot != foeSlot)
                    decodeMon(enemySlots.getOrNull(partnerSlot))?.let { p ->
                        if (p.optInt("maxHp") > 0 && p.optInt("level") in 1..100) {
                            val po = JSONObject(); po.put("species", p.optString("species")); po.put("level", p.optInt("level"))
                            e.put("partner", po)
                        }
                    }
                    // The opponent's WHOLE party. Gating the doubles partner on
                    // BATTLE_TYPE_DOUBLE fixed a wrong "partner" readout but took
                    // away the only view of a trainer's bench — and the moment you
                    // most need it is "X is about to send out Y", deciding whether
                    // to stay in. Slots that don't decode are simply absent, so a
                    // wild battle yields a single-entry list.
                    val team = JSONArray()
                    // Do NOT assume the enemy party is contiguous. A two-trainer
                    // double lays each trainer's mons out in its own sub-range,
                    // so a real battle read slots 0,1,3,4 with a HOLE at 2 — the
                    // old stop-at-first-empty scan quit there and never saw the
                    // second trainer's Pokémon at all. Skip empties, don't stop.
                    for (s in 0 until 6) {
                        val tm = decodeMon(enemySlots.getOrNull(s)) ?: continue
                        if (tm.optInt("maxHp") <= 0 || tm.optInt("level") !in 1..100) continue
                        val to = JSONObject()
                        to.put("species", tm.optString("species"))
                        to.put("level", tm.optInt("level"))
                        to.put("hp", tm.optInt("hp"))
                        to.put("maxHp", tm.optInt("maxHp"))
                        // Their actual moveset, straight out of the same struct
                        // layout as the player's party. Knowing what a foe can
                        // DO matters more than its stats — a mon you switch in
                        // with two super-effective attacks is still a bad trade
                        // if it eats a super-effective hit first.
                        tm.optJSONArray("moves")?.let { to.put("moves", it) }
                        tm.optString("item").takeIf { it.isNotEmpty() }?.let { to.put("item", it) }
                        // In doubles TWO of them are out; marking only foeSlot
                        // made the second on-field foe look like a bench mon
                        // (and the tracker then offered to "scout" something
                        // already staring at you).
                        to.put("slot", s)
                        // Battler position, so the tracker can order/label these
                        // the way the SCREEN does. Gen-3 names positions from
                        // each side's own perspective, so OPPONENT_LEFT (1)
                        // actually renders on the PLAYER'S RIGHT and
                        // OPPONENT_RIGHT (3) on the player's left — confirmed
                        // in game. Everything keyed off identity (party slot)
                        // was already correct; only the left/right labelling
                        // was inverted.
                        // Ordering hint only (no left/right claim is made in the
                        // UI any more). Kept consistent with the target mapping
                        // above so the columns and the focus agree.
                        if (isDouble && s == foe2Slot) to.put("pos", 1)
                        else if (s == foeSlot) to.put("pos", 3)
                        to.put("active", s == foeSlot || (isDouble && s == foe2Slot))
                        team.put(to)
                    }
                    if (team.length() > 0) e.put("team", team)
                    // Which foe your cursor is currently on (party slot, matching
                    // the "slot" field on each team entry).
                    if (targetBattler >= 0 && isDouble) {
                        // Cursor value -> which foe. Battler 1 is gBattlerPartyIndexes[1]
                        // and battler 3 is [3]; the ids are the opponent's own left/right
                        // so they read mirrored on screen (1 sits on YOUR right).
                        //
                        // This was inverted until v0.74. The previous pairing was recorded
                        // as "determined by observation on device", but it was calibrated
                        // against a targetCursor address that read 0 in every battle — so
                        // targetBattler was always -1 and this branch never actually ran.
                        // The observation described a code path that could not execute.
                        //
                        // Pinned properly from a live Odyssey double: with the LEFT foe
                        // (Porygon, enemy party slot 1) highlighted the cursor read 3, and
                        // with the RIGHT foe (Mawile, slot 0) it read 1 —
                        // gBattlerPartyIndexes was [0,0,1,1], so 1 -> foeSlot and
                        // 3 -> foe2Slot.
                        e.put("targetSlot", if (targetBattler == 1) foeSlot else foe2Slot)
                    }
                    e.remove("hp"); e.remove("maxHp"); e.remove("status")
                    encounter = e
                }
            }
        }

        // Game clock (raw RTC struct; Time Turner offset TBD — see profile note).
        var timeOfDay: String? = null
        var gameHourNow: Int? = null
        if (a.gameHour != 0L) read(sock, addr, a.gameHour, 1)?.let { hb ->
            val hour = hb[0].toInt() and 0xFF
            if (hour in 0..23) {
                gameHourNow = hour
                // Two-way day/night is all the vanilla games need. Lazarus has FOUR periods
                // (morning / noon / evening / night) and an inn that sets them, so a profile
                // may declare its own bands. Each band is "name:start-end" with wrap allowed,
                // so night can be 21-3. Falls back to the old rule when absent, leaving every
                // other profile exactly as it was.
                val bands = profile.hourBands
                timeOfDay = if (bands.isEmpty()) {
                    if (hour in 6..19) "day" else "night"
                } else {
                    bands.firstOrNull { (_, lo, hi) ->
                        if (lo <= hi) hour in lo..hi else (hour >= lo || hour <= hi)
                    }?.first
                }
            }
        }
        // Sweep one PC box per poll while out of battle. Catches made with a
        // full party go straight to storage and never touch the party struct,
        // so without this they are invisible to the tracker entirely.
        // Two ways to reach the storage struct, because not every build has a pointer to
        // dereference. Emerald keeps gPokemonStoragePtr; Pisces does NOT — gPokemonStorage
        // is a static EWRAM object there, and a scan of all of EWRAM and IWRAM for its
        // address turned up nothing to follow. storageBase names the struct directly for
        // those, and takes precedence when both are present.
        if (!inBattle && (a.storagePtr != 0L || a.storageBase != 0L)) {
            val ptrRead: ByteArray? =
                if (a.storageBase != 0L) ByteArray(4).also { buf ->
                    var v = a.storageBase
                    for (i in 0 until 4) { buf[i] = (v and 0xFF).toByte(); v = v shr 8 }
                } else read(sock, addr, a.storagePtr, 4)
            ptrRead?.let { pb ->
                val storage = u32(pb, 0)
                if (storage > 0x02000000L && storage < 0x03000000L) {
                    // Box records are NOT always 80 bytes. CFRU stores them compressed —
                    // Unbound's are 58 — and walking a compressed box at the vanilla stride
                    // reads slot 0 correctly and then lands mid-record for every slot after
                    // it, so a PC with five Pokemon reported one. A catch made with a full
                    // party goes straight to the box, so that is the catch itself going
                    // missing.
                    // TWO different numbers, and conflating them misaligns every box after
                    // the first. boxStride is the size of one SLOT. boxSpan is the distance
                    // from one BOX to the next, which is not the same thing on a compressed
                    // layout: Unbound's records are 58 bytes, so 30 of them fill 1740, and
                    // then 660 bytes of zero padding run to the next box at 2400. Proven by
                    // reading it — bytes 1740..2399 of box 1 are entirely zero, and the box
                    // NAMES sit at base+0x8344, which is 4 + 14*2400.
                    val stride = a.boxStride
                    val boxBytes = 30 * stride
                    // Bytes before the box array inside gPokemonStorage. Vanilla is 4 (a u8
            // currentBox plus padding). Tourmaline uses 48: its box names sit at
            // base+0x8370 rather than base+0x8344, and 0x8370-48 is exactly
            // 14*30*80 = 33600, so the ARRAY is standard and only the prologue differs.
            // Hardcoding 4 would have read every box 44 bytes early.
            val boxBase = storage + a.boxesOffset + boxCursor.toLong() * a.boxSpan.toLong()
                    val blk = ByteArray(boxBytes)
                    var ok = true
                    var got = 0
                    while (got < boxBytes) {
                        val want = minOf(800, boxBytes - got)
                        val part = read(sock, addr, boxBase + got.toLong(), want)
                        if (part == null || part.size < want) { ok = false; break }
                        System.arraycopy(part, 0, blk, got, want)
                        got += want
                    }
                    if (ok) {
                        val list = mutableListOf<JSONObject>()
                        for (slot in 0 until 30) decodeBoxMon(blk, slot * stride, stride)?.let { list.add(it) }
                        boxContents[boxCursor] = list
                        boxSweptAt[boxCursor] = System.currentTimeMillis()
                    } else {
                        // Could not confirm this box — drop what we think we know
                        // rather than keep serving it. A cached box is the one
                        // piece of state that outlives everything short of a
                        // restart, so an unconfirmed entry is exactly the kind of
                        // thing that lingers as a phantom.
                        boxContents[boxCursor] = mutableListOf()
                        boxSweptAt[boxCursor] = 0L
                    }
                    boxCursor = (boxCursor + 1) % 14
                }
            }
        }
        // Sanity-check the read against the loaded profile. Every address here
        // is per-GAME, so pointing the wrong profile at a running game decodes
        // cleanly-shaped nonsense — a plausible party count, species ids that
        // resolve to the wrong names or to "#1234" placeholders — with nothing
        // upstream looking broken. That is indistinguishable from a bug unless
        // it is called out, so say it here rather than let it read as live truth.
        run {
            val placeholders = (0 until party.length()).count {
                party.getJSONObject(it).optString("species").startsWith("#")
            }
            val bad = count > 6 || (party.length() > 0 && placeholders * 2 >= party.length())
            if (bad) {
                lastError = "Profile may not match the running game — " +
                    "party reads $count with $placeholders unnamed species. " +
                    "Check the Game selection above matches what is loaded."
            } else if (lastError.startsWith("Profile may not match")) {
                lastError = "—"
            }
        }
        BridgeCore.lastMemoryPollAt = System.currentTimeMillis()
        val state = JSONObject()
        state.put("type", "state")
        state.put("source", "memory")
        state.put("game", profile.game)
        // Active battler → allies signal: the tracker's existing "Your moves"
        // auto-select follows whoever is actually on the field (switch-aware —
        // gBattlerPartyIndexes[0] verified via user RAM snapshot).
        if (inBattle && mySlot in 0 until party.length()) {
            val allies = JSONArray()
            allies.put(party.getJSONObject(mySlot).optString("species"))
            // Doubles: your partner slot is on the field too, so it belongs in
            // the allies list the battle panel matches against.
            if (isDouble && mySlot2 in 0 until party.length() && mySlot2 != mySlot) {
                allies.put(party.getJSONObject(mySlot2).optString("species"))
            }
            state.put("allies", allies)
        }
        // The mon whose move you are picking — the tracker focuses it so the
        // move list always belongs to whoever the game is asking about.
        if (choosingBattler == 0 || choosingBattler == 2) {
            val slot = if (choosingBattler == 0) mySlot else mySlot2
            if (slot in 0 until party.length()) {
                state.put("choosing", party.getJSONObject(slot).optString("species"))
            }
        }
        run {
            // Only report boxes confirmed RECENTLY. The rotation covers all 14
            // in about 14 seconds, so anything older than a minute means the
            // sweep stalled — and stale box contents are worse than none, since
            // the tracker treats an unknown mon as a real catch and adds it to
            // the run. Loading a savestate is the case that bites: the world
            // changes wholesale while the cache still describes the old one.
            val fresh = System.currentTimeMillis() - 60000
            val boxArr = JSONArray()
            for (i in boxContents.indices) if (boxSweptAt[i] > fresh) for (m in boxContents[i]) boxArr.put(m)
            if (boxArr.length() > 0) state.put("box", boxArr)
        }
        if (route != null) state.put("route", route)
        // Which of the region's maps this actually is. Sent alongside the name so a
        // consumer can distinguish sub-areas that share one; nothing is required to use it.
        mapId?.let { state.put("mapId", it) }
        gameHourNow?.let { state.put("gameHour", it) }
        surfing?.let { state.put("surfing", it) }
        if (timeOfDay != null) state.put("timeOfDay", timeOfDay)
        state.put("party", party)
        state.put("encounter", encounter ?: JSONObject.NULL)
        val cmp = state.toString()
        lastStateSummary = buildString {
            append('[').append(profile.game).append("] ")
            append(route ?: "?")
            append(" · party ").append(party.length())
            encounter?.let { append(" · vs ").append(it.optString("species")).append(" [").append(kind).append("]") }
            // Live readout of the two cursors, so a mis-pinned address is
            // visible on this screen instead of needing another snapshot round
            // trip: watch "turn" change as the game asks each of your mons, and
            // "tgt" change as you move the target cursor.
            if (inBattle) {
                append(" · turn=").append(if (choosingBattler >= 0) choosingBattler.toString() else "?")
                append(" tgt=").append(if (targetRaw >= 0) targetRaw.toString() else "?")
            }
        }
        // Broadcast on CHANGE, or on a heartbeat if nothing has changed for a
        // while. Change-only emission meant a player standing still sent no
        // frames at all, which is indistinguishable from a dead feed — the
        // tracker's staleness warning fired on a perfectly healthy bridge and
        // only cleared when something moved. A floor interval keeps the feed
        // demonstrably alive without making it chatty: on loopback this is a few
        // hundred bytes every couple of seconds.
        val now = System.currentTimeMillis()
        val heartbeat = now - lastBroadcastAt >= HEARTBEAT_MS
        if (cmp != lastJson || heartbeat) {
            lastBroadcastAt = now
            lastJson = cmp
            state.put("ts", System.currentTimeMillis())
            BridgeCore.lastState = state
            BridgeCore.lastEmit = state.toString()
            BridgeCore.server?.broadcastState(state)
            BridgeCore.notifyChanged()
        }
    }

    companion object {
        val NATURES = listOf(
            "Hardy","Lonely","Brave","Adamant","Naughty","Bold","Docile","Relaxed","Impish","Lax",
            "Timid","Hasty","Serious","Jolly","Naive","Modest","Mild","Quiet","Bashful","Rash",
            "Calm","Gentle","Sassy","Careful","Quirky")
        // Total exp at level n per Gen-3 growth enum (0 MedFast,1 Erratic,
        // 2 Fluctuating,3 MedSlow,4 Fast,5 Slow). Integer math as the game does.
        fun expAt(growth: Int, n: Int): Int {
            val n3 = n * n * n
            return when (growth) {
                0 -> n3
                1 -> when {                                   // Erratic
                    n <= 50 -> n3 * (100 - n) / 50
                    n <= 68 -> n3 * (150 - n) / 100
                    n <= 98 -> n3 * ((1911 - 10 * n) / 3) / 500
                    else -> n3 * (160 - n) / 100
                }
                2 -> when {                                   // Fluctuating
                    n <= 15 -> n3 * (((n + 1) / 3) + 24) / 50
                    n <= 36 -> n3 * (n + 14) / 50
                    else -> n3 * ((n / 2) + 32) / 50
                }
                3 -> 6 * n3 / 5 - 15 * n * n + 100 * n - 140  // Medium Slow
                4 -> 4 * n3 / 5                               // Fast
                else -> 5 * n3 / 4                            // Slow
            }
        }
        /** Decoded gBattleTypeFlags. */
        data class BattleKind(val known: Boolean, val trainer: Boolean, val double: Boolean)
        /**
         * gBattleTypeFlags → what kind of battle this is. Bits: 0x1 DOUBLE,
         * 0x4 IS_MASTER, 0x8 TRAINER. Values observed live on the Thor:
         *   0x4        wild single
         *   0xc        trainer single
         *   0x20000d   trainer DOUBLE (+ a CFRU flag at 0x200000)
         * The high bit in that last one is why we must NOT require the value to
         * fit in 16 bits — an earlier version did, rejected the real double
         * battle, and reported it as a wild single.
         */
        fun battleKind(v: Long): BattleKind =
            if ((v and 0x4L) != 0L && v != 0xFFFFFFFFL)
                BattleKind(true, (v and 0x8L) != 0L, (v and 0x1L) != 0L)
            else BattleKind(false, false, false)

        /**
         * Gen-3 in-game text → ASCII. Same table the desktop tooling uses:
         * 0x00 space, 0xA1.. digits, 0xBB.. A-Z, 0xD5.. a-z, 0xFF terminator.
         * Returns null if it hits a byte outside the set, so a garbled read
         * yields nothing rather than mojibake.
         */
        fun decodeG3(b: ByteArray, off: Int, max: Int): String? {
            val sb = StringBuilder()
            for (i in 0 until max) {
                if (off + i >= b.size) break
                val c = b[off + i].toInt() and 0xFF
                when {
                    c == 0xFF -> return sb.toString().trim()
                    c == 0x00 -> sb.append(' ')
                    c in 0xBB..0xD4 -> sb.append(('A' + (c - 0xBB)))
                    c in 0xD5..0xEE -> sb.append(('a' + (c - 0xD5)))
                    c in 0xA1..0xAA -> sb.append(('0' + (c - 0xA1)))
                    c == 0xAD -> sb.append('.')
                    c == 0xAE -> sb.append('-')
                    c == 0xB4 -> sb.append(0x27.toChar())
                    c == 0xB5 -> sb.append('♂')
                    c == 0xB6 -> sb.append('♀')
                    else -> return null
                }
            }
            return sb.toString().trim()
        }

        /**
         * Re-send unchanged state at least this often. Comfortably inside the
         * tracker's 8 s staleness threshold, so two beats can be lost before it
         * warns — enough tolerance that a single slow poll is not reported as a
         * failure, while a genuinely dead feed still surfaces quickly.
         */
        private const val HEARTBEAT_MS = 2500L

        private val ORDERS = listOf(
            "GAEM","GAME","GEAM","GEMA","GMAE","GMEA","AGEM","AGME","AEGM","AEMG","AMGE","AMEG",
            "EGAM","EGMA","EAGM","EAMG","EMGA","EMAG","MGAE","MGEA","MAGE","MAEG","MEGA","MEAG"
        )
    }
}

/** Loaded from assets/memory/<game>.json (dump-memory-profile.mjs output). */
class MemoryProfile(json: JSONObject) {
    val game: String = json.optString("game", "unbound")
    /** Bytes of experience stored at Growth+4. Vanilla is 4; Lazarus uses 2. */
    val expWidth: Int = json.optInt("expWidth", 4)
    /** Grace period before a low battle flag is believed. Default ZERO.
     *
     *  A hold is not the right tool for the two things that actually go wrong. A dropped
     *  UDP read is handled separately and explicitly (a null read holds the previous
     *  state, because a lost packet is not evidence a battle ended). And a flag that
     *  genuinely reads 0 mid-battle means the profile is pointing at the wrong address —
     *  the fix is the address, not a timer.
     *
     *  This existed at 10s, then 1.2s, to work around Lazarus's flag, which turned out
     *  not to be a battle flag at all: it tracked the active SCREEN and went low whenever
     *  a menu opened. Once its profile was pointed at a battle-allocation pointer the
     *  workaround had no job left, but every game was still paying it as latency on the
     *  battle-to-overworld transition.
     *
     *  Kept as a per-profile escape hatch (`battleFlagHoldMs`) for a game whose flag is
     *  later found to dip for reasons that cannot be fixed by choosing a better address. */
    val battleHoldMs: Long = json.optLong("battleFlagHoldMs", 0L)
    val addrs = Addrs(json.getJSONObject("addrs"))
    val speciesById: Map<Int, String> = json.getJSONObject("speciesById").let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    val sectionNames: Map<Int, String> = json.getJSONObject("sectionNames").let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    // "mapGroup-mapNum" -> the name to show instead of whatever the map header claims.
    // Only for maps whose regionMapSectionId is wrong in the ROM. Optional and empty
    // by default, so no profile changes behaviour unless it opts in.
    val mapOverrides: Map<String, String> = (json.optJSONObject("mapOverrides") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it to o.getString(it) }
    }
    // Optional time-of-day bands, as ["morning:4-9", "day:10-17", ...]. Wrap is allowed so
    // "night:21-3" means 21,22,23,0,1,2,3. Empty leaves the two-way day/night default.
    // Bit index within the Misc word AFTER the IVs (the vanilla ribbons word) that holds
    // the ability slot, for builds that moved it off IV-word bit 31. -1 = vanilla behaviour.
    val abilitySlotWord2Bit: Int = json.optInt("abilitySlotWord2Bit", -1)
    val hourBands: List<Triple<String, Int, Int>> = (json.optJSONArray("hourBands") ?: org.json.JSONArray()).let { arr ->
        (0 until arr.length()).mapNotNull { i ->
            val parts = arr.optString(i).split(":", "-")
            if (parts.size == 3) Triple(parts[0], parts[1].toIntOrNull() ?: return@mapNotNull null,
                                        parts[2].toIntOrNull() ?: return@mapNotNull null) else null
        }
    }
    val growthById: Map<Int, Int> = (json.optJSONObject("growthById") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getInt(it) }
    }
    val movesById: Map<Int, String> = (json.optJSONObject("movesById") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    val itemsById: Map<Int, String> = (json.optJSONObject("itemsById") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { it.toInt() to o.getString(it) }
    }
    /** species id → [type1, type2], dumped from the ROM's own tables. */
    val typeBySpecies: Map<Int, List<String>> = (json.optJSONObject("typeBySpecies") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { k ->
            val arr = o.getJSONArray(k)
            k.toInt() to (0 until arr.length()).map { arr.getString(it) }
        }
    }
    /** species id → ability names by slot, dumped from the ROM's own tables. */
    val abilityBySpecies: Map<Int, List<String>> = (json.optJSONObject("abilityBySpecies") ?: JSONObject()).let { o ->
        o.keys().asSequence().associate { k ->
            val arr = o.getJSONArray(k)
            k.toInt() to (0 until arr.length()).map { arr.getString(it) }
        }
    }
    class Addrs(o: JSONObject) {
        val partyCount = o.getLong("partyCount")
        val playerParty = o.getLong("playerParty")
        val enemyParty = o.getLong("enemyParty")
        val gMapHeader = o.getLong("gMapHeader")
        // gSaveBlock1Ptr — optional; without it a profile simply reports no mapId.
        val saveBlock1Ptr = o.optLong("saveBlock1Ptr", 0L)
        // gPlayerAvatar. Its first byte is a flag bitmask: bit 0 ON_FOOT, bit 1 MACH_BIKE,
        // bit 2 ACRO_BIKE, bit 3 SURFING, bit 4 UNDERWATER. Optional — a profile without it
        // simply reports no movement state, exactly as before.
        val playerAvatar = o.optLong("playerAvatar", 0L)
        val sectionIdOff = o.getInt("sectionIdOff")
        val inBattle = o.getLong("inBattle")
        // How to READ that byte. Two different signals wear the same field:
        //   "bool"    — gMain.inBattle, a genuine flag in IWRAM. Non-zero means battle.
        //   "ptrHigh" — the top byte of a battle-allocation POINTER in EWRAM. Only 0x02
        //               means "allocated", because that is what an EWRAM address starts
        //               with. Any other value is whatever else happens to live there.
        // Treating a ptrHigh profile as a bool is how the PC screen registered as a
        // battle on Pisces: the byte reads 0xf0 standing at the box system, which is
        // non-zero, so every menu that touched that allocator looked like a fight.
        val inBattlePtrHigh = o.optString("inBattleMode", "bool") == "ptrHigh"
        // Which BITS of that byte mean "in battle". gMain+0x439 is a bitfield, not a
        // plain bool — TRE Johto reads 2 in battle because inBattle is bit 1, while
        // bit 0 (oamLoadDisabled) is free to be set on its own. Masking says exactly
        // which bit we mean instead of accepting any non-zero value. Default 0xFF
        // keeps every existing profile on the old "non-zero" test unchanged.
        val inBattleMask = o.optInt("inBattleMask", 0xFF)
        val gameHour = o.optLong("gameHour", 0L)
        val battlerIndexes = o.optLong("battlerIndexes", 0L)
        val battleTypeFlags = o.optLong("battleTypeFlags", 0L)
        val battlersCount = o.optLong("battlersCount", 0L)
        val execFlags = o.optLong("execFlags", 0L)
        val targetCursor = o.optLong("targetCursor", 0L)
        val storagePtr = o.optLong("storagePtr", 0L)
        // Offset of the box array within gPokemonStorage. 4 in vanilla; a build may put
        // more in front of it (Tourmaline: 48). Verified per game against the box-name
        // address, which must land at boxesOffset + boxCount*boxSpan.
        val boxesOffset = o.optInt("boxesOffset", 4)
        // Bytes per box slot. 80 is the vanilla Gen-3 BoxPokemon; CFRU compresses it (58 on
        // Unbound, verified against live RAM — five Pokemon in box 1 that the 80-byte walk
        // could not see past the first).
        val boxStride = o.optInt("boxStride", 80)
        // Bytes from one box to the next. Defaults to the vanilla 30*80, which is also what
        // a compressed layout uses when its records are padded out to the same box size.
        val boxSpan = o.optInt("boxSpan", 30 * 80)
        // The storage struct's address itself, for builds with no pointer variable to
        // follow. Verified on Pisces by two independent derivations meeting: the box-name
        // array sits at base+0x8344, and base+12 is box 1 slot 0's nickname, which read
        // "Patty" seconds after she was deposited into box 1.
        val storageBase = o.optLong("storageBase", 0L)
    }
}
